package io.github.dfa1.vortex.fbsgen;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/// Emits MemorySegment-native FlatBuffers reader/builder classes from a [TypeRegistry].
///
/// One `.java` file per declaration:
/// - each `table` becomes a `final class extends FbsTable` with read accessors plus
///   `createX`/`startX`/`addX`/`endX`/`finishXBuffer` builders;
/// - each `struct` becomes a `final class extends FbsMemorySegment` with inline-offset accessors
///   and an inline `createX` builder;
/// - each `enum` becomes a constants holder over its underlying integer type;
/// - each `union` becomes a discriminator-constants holder (NONE = 0, members from 1).
///
/// The wire layout is the standard FlatBuffers binary format — see [FbsTable]/[FbsBuilder].
public final class CodeGen {

    /// Prefix applied to every emitted Java class name so the generated wire-format
    /// classes (`Array`, `DType`, `Bool`, `List`, …) do not collide with project or JDK
    /// types of the same name. Schema files keep the upstream (unprefixed) names; the
    /// prefix lives here, mirroring proto-gen's `JAVA_NAME_PREFIX`.
    private static final String JAVA_NAME_PREFIX = "Fbs";

    private static final String GENERATED_ANNOTATION = "@Generated(\"io.github.dfa1.vortex.fbsgen.CodeGen\")\n";

    private final TypeRegistry registry;

    /// @param registry resolved schema model
    public CodeGen(TypeRegistry registry) {
        this.registry = registry;
    }

    /// Emits every declaration to `outDir`, one file per type.
    ///
    /// @param outDir output directory (the package directory)
    /// @throws IOException on filesystem errors
    public void emit(Path outDir) throws IOException {
        Files.createDirectories(outDir);
        for (Ast.Decl decl : registry.all()) {
            String src = switch (decl) {
                case Ast.TableDecl t -> emitTable(t);
                case Ast.StructDecl s -> emitStruct(s);
                case Ast.EnumDecl e -> emitEnum(e);
                case Ast.UnionDecl u -> emitUnion(u);
            };
            Files.writeString(outDir.resolve(className(decl.name()) + ".java"), src);
        }
    }

    private String preamble(String importBlock) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by vortex-fbs-gen. Do not edit.\n\n");
        sb.append("package ").append(registry.javaPackage()).append(";\n\n");
        sb.append(importBlock);
        sb.append("import javax.annotation.processing.Generated;\n\n");
        return sb.toString();
    }

    /// Maps a schema type name to its generated Java class name (prefixed).
    ///
    /// @param schemaName the name as written in the `.fbs` schema
    /// @return the Java class name
    private static String className(String schemaName) {
        String base = schemaName.endsWith("_") ? schemaName.substring(0, schemaName.length() - 1) : schemaName;
        return JAVA_NAME_PREFIX + base;
    }

    // ---- tables ---------------------------------------------------------------

    private String emitTable(Ast.TableDecl table) {
        String name = className(table.name());
        StringBuilder sb = new StringBuilder();
        sb.append(preamble("import java.lang.foreign.MemorySegment;\n"));
        sb.append("/// Reader and builder for the `").append(table.name()).append("` FlatBuffers table.\n");
        sb.append(GENERATED_ANNOTATION);
        sb.append("public final class ").append(name).append(" extends FbsTable {\n\n");

        sb.append("""
                    /// Positions a reader at the root table of a finished buffer.
                    /// @param seg the buffer
                    /// @return a reader positioned at the root
                    public static %1$s getRootAs%1$s(MemorySegment seg) {
                        return new %1$s().assign(seg, FbsTable.rootPosition(seg, 0));
                    }

                """.formatted(name));

        sb.append("""
                    /// Positions this reader at a table.
                    /// @param seg the buffer
                    /// @param position the table position
                    /// @return this
                    public %s assign(MemorySegment seg, long position) {
                        init(seg, position);
                        return this;
                    }
                """.formatted(name));

        int vtableIndex = 0;
        for (Ast.Field field : table.fields()) {
            vtableIndex = emitTableField(sb, field, vtableIndex);
        }
        emitTableBuilder(sb, table);
        sb.append("}\n");
        return sb.toString();
    }

    /// Emits accessors for one table field; returns the next vtable index (a union
    /// consumes two slots: discriminator + value).
    private int emitTableField(StringBuilder sb, Ast.Field field, int vtableIndex) {
        String accessor = camelCase(field.name());
        Ast.FieldType type = field.type();
        int vt = 4 + vtableIndex * 2;

        if (type instanceof Ast.Scalar scalar) {
            emitScalarTableField(sb, accessor, scalar, vt, field.defaultValue().orElse(null));
            return vtableIndex + 1;
        }
        if (type instanceof Ast.Vector vector) {
            emitVectorField(sb, accessor, vector.element(), vt);
            return vtableIndex + 1;
        }
        Ast.Ref ref = (Ast.Ref) type;
        Ast.Decl target = registry.resolve(ref);
        return switch (target) {
            case Ast.EnumDecl e -> {
                emitScalarTableField(sb, accessor, e.underlying(), vt, field.defaultValue().orElse(null));
                yield vtableIndex + 1;
            }
            case Ast.UnionDecl _ -> {
                emitUnionField(sb, accessor, vt);
                yield vtableIndex + 2;
            }
            case Ast.TableDecl t -> {
                emitObjectField(sb, accessor, className(t.name()), vt, true);
                yield vtableIndex + 1;
            }
            case Ast.StructDecl s -> {
                emitObjectField(sb, accessor, className(s.name()), vt, false);
                yield vtableIndex + 1;
            }
        };
    }

    private void emitScalarTableField(StringBuilder sb, String accessor, Ast.Scalar scalar, int vt, String defaultValue) {
        ScalarIo io = scalarIo(scalar);
        String read = io.tableRead();
        sb.append("\n    /// @return the `").append(accessor).append("` field\n");
        if (scalar == Ast.Scalar.BOOL) {
            boolean def = "true".equals(defaultValue);
            sb.append("""
                        public boolean %1$s() {
                            int o = fieldOffset(%2$d);
                            return o != 0 ? readByte(pos + o) != 0 : %3$b;
                        }
                    """.formatted(accessor, vt, def));
        } else {
            String def = defaultLiteral(io, defaultValue);
            sb.append("""
                        public %1$s %2$s() {
                            int o = fieldOffset(%3$d);
                            return o != 0 ? %4$s : %5$s;
                        }
                    """.formatted(io.javaType, accessor, vt, read, def));
        }
        if ("null".equals(defaultValue)) {
            sb.append("""

                        /// @return whether the optional `%1$s` field is present
                        public boolean has%2$s() {
                            return fieldOffset(%3$d) != 0;
                        }
                    """.formatted(accessor, capitalize(accessor), vt));
        }
    }

    private void emitObjectField(StringBuilder sb, String accessor, String typeName, int vt, boolean indirect) {
        String target = indirect ? "indirect(pos + o)" : "pos + o";
        sb.append("""

                    /// @return the `%1$s` child, or null if absent
                    public %2$s %1$s() {
                        int o = fieldOffset(%3$d);
                        return o != 0 ? new %2$s().assign(seg, %4$s) : null;
                    }
                """.formatted(accessor, typeName, vt, target));
    }

    private void emitUnionField(StringBuilder sb, String accessor, int vtType) {
        int vtValue = vtType + 2;
        sb.append("""

                    /// @return the union discriminator for `%1$s` (0 = none)
                    public int %1$sType() {
                        int o = fieldOffset(%2$d);
                        return o != 0 ? readByte(pos + o) & 0xFF : 0;
                    }

                    /// Projects the selected `%1$s` member onto the given reader.
                    /// @param obj a reader for the expected member type
                    /// @param <T> the member reader type
                    /// @return the positioned reader, or null if the union is absent
                    public <T extends FbsTable> T %1$s(T obj) {
                        int o = fieldOffset(%3$d);
                        return o != 0 ? locate(obj, unionMemberPosition(o)) : null;
                    }
                """.formatted(accessor, vtType, vtValue));
    }

    private void emitVectorField(StringBuilder sb, String accessor, Ast.FieldType element, int vt) {
        sb.append("""

                    /// @return the length of the `%1$s` vector
                    public int %1$sLength() {
                        int o = fieldOffset(%2$d);
                        return o != 0 ? vectorLength(o) : 0;
                    }
                """.formatted(accessor, vt));

        if (element instanceof Ast.Scalar scalar) {
            emitScalarVectorElements(sb, accessor, scalar, vt);
            return;
        }
        Ast.Ref ref = (Ast.Ref) element;
        Ast.Decl target = registry.resolve(ref);
        switch (target) {
            case Ast.EnumDecl e -> emitScalarVectorElements(sb, accessor, e.underlying(), vt);
            case Ast.TableDecl t -> emitObjectVectorElement(sb, accessor, className(t.name()), vt, 4, true);
            case Ast.StructDecl s -> emitObjectVectorElement(sb, accessor, className(s.name()), vt, registry.layoutOf(s).size(), false);
            case Ast.UnionDecl _ -> throw new FbsParseException("vectors of unions are not supported ('" + accessor + "')");
        }
    }

    private void emitScalarVectorElements(StringBuilder sb, String accessor, Ast.Scalar scalar, int vt) {
        if (scalar == Ast.Scalar.STRING) {
            sb.append("""

                        /// @param j element index
                        /// @return the j-th `%1$s` string
                        public String %1$s(int j) {
                            int o = fieldOffset(%2$d);
                            return readStringAt(vectorElements(o) + (long) j * 4);
                        }
                    """.formatted(accessor, vt));
            return;
        }
        ScalarIo io = scalarIo(scalar);
        int size = TypeRegistry.sizeOf(scalar);
        sb.append("""

                    /// @param j element index
                    /// @return the j-th `%1$s` element
                    public %2$s %1$s(int j) {
                        int o = fieldOffset(%3$d);
                        return %4$s;
                    }
                """.formatted(accessor, io.javaType, vt, io.vectorRead(size)));
        if (scalar == Ast.Scalar.UINT8 || scalar == Ast.Scalar.INT8) {
            sb.append("""

                        /// @return a zero-copy slice of the `%1$s` byte vector, or null if absent
                        public MemorySegment %1$sAsSegment() {
                            int o = fieldOffset(%2$d);
                            return o != 0 ? byteVector(o) : null;
                        }
                    """.formatted(accessor, vt));
        }
    }

    private void emitObjectVectorElement(StringBuilder sb, String accessor, String typeName, int vt, int stride, boolean indirect) {
        String base = "vectorElements(o) + (long) j * " + stride;
        String target = indirect ? "indirect(" + base + ")" : base;
        sb.append("""

                    /// @param j element index
                    /// @return the j-th `%1$s` element
                    public %2$s %1$s(int j) {
                        int o = fieldOffset(%3$d);
                        return new %2$s().assign(seg, %4$s);
                    }
                """.formatted(accessor, typeName, vt, target));
    }

    // ---- structs --------------------------------------------------------------

    private String emitStruct(Ast.StructDecl struct) {
        String name = className(struct.name());
        TypeRegistry.StructLayout layout = registry.layoutOf(struct);
        StringBuilder sb = new StringBuilder();
        sb.append(preamble("import java.lang.foreign.MemorySegment;\n"));
        sb.append("/// Reader and builder for the `").append(struct.name()).append("` FlatBuffers struct (inline, ")
                .append(layout.size()).append(" bytes).\n");
        sb.append(GENERATED_ANNOTATION);
        sb.append("public final class ").append(name).append(" extends FbsMemorySegment {\n\n");
        sb.append("""
                    /// Positions this reader at a struct.
                    /// @param seg the buffer
                    /// @param position the struct position
                    /// @return this
                    public %s assign(MemorySegment seg, long position) {
                        init(seg, position);
                        return this;
                    }
                """.formatted(name));

        for (int i = 0; i < struct.fields().size(); i++) {
            Ast.Field field = struct.fields().get(i);
            int off = layout.fieldOffsets()[i];
            Ast.Scalar scalar = structFieldScalar(field);
            emitScalarStructField(sb, camelCase(field.name()), scalar, off);
        }
        emitStructBuilder(sb, struct, layout);
        sb.append("}\n");
        return sb.toString();
    }

    private Ast.Scalar structFieldScalar(Ast.Field field) {
        if (field.type() instanceof Ast.Scalar s) {
            return s;
        }
        return ((Ast.EnumDecl) registry.resolve((Ast.Ref) field.type())).underlying();
    }

    private void emitScalarStructField(StringBuilder sb, String accessor, Ast.Scalar scalar, int off) {
        ScalarIo io = scalarIo(scalar);
        sb.append("\n    /// @return the `").append(accessor).append("` field\n");
        if (scalar == Ast.Scalar.BOOL) {
            sb.append("""
                        public boolean %1$s() {
                            return readByte(%2$d) != 0;
                        }
                    """.formatted(accessor, off));
        } else {
            sb.append("""
                        public %1$s %2$s() {
                            return %3$s;
                        }
                    """.formatted(io.javaType, accessor, io.structRead(off)));
        }
    }

    // ---- enums & unions -------------------------------------------------------

    private String emitEnum(Ast.EnumDecl e) {
        String constType = enumConstType(e.underlying());
        StringBuilder sb = new StringBuilder();
        String name = className(e.name());
        sb.append(preamble(""));
        sb.append("/// Constants for the `").append(e.name()).append("` FlatBuffers enum.\n");
        sb.append(GENERATED_ANNOTATION);
        sb.append("public final class ").append(name).append(" {\n\n");
        sb.append("    private ").append(name).append("() {\n    }\n");
        long next = 0;
        for (Ast.EnumVal v : e.values()) {
            long value = v.number().isPresent() ? v.number().getAsInt() : next;
            next = value + 1;
            sb.append("""

                        /// `%1$s` = %2$d
                        public static final %3$s %1$s = %4$s;
                    """.formatted(v.name(), value, constType, literal(constType, value)));
        }
        sb.append("}\n");
        return sb.toString();
    }

    private String emitUnion(Ast.UnionDecl u) {
        StringBuilder sb = new StringBuilder();
        String name = className(u.name());
        sb.append(preamble(""));
        sb.append("/// Discriminator constants for the `").append(u.name()).append("` FlatBuffers union.\n");
        sb.append(GENERATED_ANNOTATION);
        sb.append("public final class ").append(name).append(" {\n\n");
        sb.append("    private ").append(name).append("() {\n    }\n");
        sb.append("\n    /// No member selected.\n");
        sb.append("    public static final byte NONE = 0;\n");
        long next = 1;
        for (Ast.UnionMember m : u.members()) {
            long value = m.number().isPresent() ? m.number().getAsInt() : next;
            next = value + 1;
            String member = className(simpleName(m.typeName()));
            sb.append("""

                        /// Member `%1$s` = %2$d
                        public static final byte %3$s = %4$s;
                    """.formatted(simpleName(m.typeName()), value, member, literal("byte", value)));
        }
        sb.append("}\n");
        return sb.toString();
    }

    // ---- table builders -------------------------------------------------------

    private void emitTableBuilder(StringBuilder sb, Ast.TableDecl table) {
        String name = className(table.name());
        List<String> params = new ArrayList<>();
        List<AddEntry> adds = new ArrayList<>();
        int slots = 0;
        for (Ast.Field field : table.fields()) {
            slots = collectBuilderField(sb, field, slots, params, adds);
        }
        // Match flatc's createX ordering: add fields by descending alignment, and within
        // an alignment group in reverse declaration order. This keeps the data region gap-free
        // and makes our output byte-identical to flatc.
        //
        // Limitation: an inline struct field (addStruct) must be the most-recently-written
        // object when it is slotted (FbsBuilder.addStruct enforces x == offset()). This holds
        // for vortex today because structs (Buffer, SegmentSpec) only ever appear as VECTOR
        // elements, never as inline table fields. If a future schema adds an inline struct
        // field that shares an alignment group with a scalar sorted ahead of it, this ordering
        // could place the scalar between the struct write and its slot and trip that guard.
        // Revisit the ordering (emit struct fields last within their group) if that ever lands.
        adds.sort((x, y) -> x.align != y.align ? Integer.compare(y.align, x.align) : Integer.compare(y.order, x.order));

        sb.append("\n    /// Builds a `").append(name).append("` table.\n");
        sb.append("    /// @param b the builder\n");
        for (String p : params) {
            sb.append("    /// @param ").append(p.substring(p.indexOf(' ') + 1)).append(" field value\n");
        }
        sb.append("    /// @return the table offset\n");
        sb.append("    public static int create").append(name).append("(FbsBuilder b");
        for (String p : params) {
            sb.append(", ").append(p);
        }
        sb.append(") {\n");
        sb.append("        b.startTable(").append(slots).append(");\n");
        for (AddEntry add : adds) {
            sb.append("        ").append(add.statement).append("\n");
        }
        sb.append("        return b.endTable();\n    }\n");

        sb.append("""

                    /// Begins a `%1$s` table.
                    /// @param b the builder
                    public static void start%1$s(FbsBuilder b) {
                        b.startTable(%2$d);
                    }

                    /// Finishes a `%1$s` table.
                    /// @param b the builder
                    /// @return the table offset
                    public static int end%1$s(FbsBuilder b) {
                        return b.endTable();
                    }

                    /// Finishes the buffer with a `%1$s` root.
                    /// @param b the builder
                    /// @param offset the root table offset
                    public static void finish%1$sBuffer(FbsBuilder b, int offset) {
                        b.finish(offset);
                    }
                """.formatted(name, slots));
    }

    /// One add-call emitted inside `createX`, tagged with its alignment and declaration
    /// order so the calls can be reordered to match flatc.
    private record AddEntry(String statement, int align, int order) {
    }

    /// Emits per-field `add*` methods (and vector helpers), and records the createX
    /// parameter list and add-call list; returns the next slot index.
    private int collectBuilderField(StringBuilder sb, Ast.Field field, int slot, List<String> params, List<AddEntry> adds) {
        String accessor = camelCase(field.name());
        String capital = capitalize(accessor);
        Ast.FieldType type = field.type();

        if (type instanceof Ast.Vector vector) {
            params.add("int " + accessor + "Offset");
            adds.add(new AddEntry("b.addOffset(" + slot + ", " + accessor + "Offset, 0);", 4, adds.size()));
            emitAddOffsetMethod(sb, accessor, capital, slot);
            emitVectorBuilders(sb, accessor, capital, vector.element());
            return slot + 1;
        }
        if (type instanceof Ast.Ref ref) {
            Ast.Decl target = registry.resolve(ref);
            if (target instanceof Ast.UnionDecl) {
                params.add("byte " + accessor + "Type");
                params.add("int " + accessor + "Offset");
                adds.add(new AddEntry("b.addByte(" + slot + ", " + accessor + "Type, 0);", 1, adds.size()));
                adds.add(new AddEntry("b.addOffset(" + (slot + 1) + ", " + accessor + "Offset, 0);", 4, adds.size()));
                emitAddByteMethod(sb, accessor + "Type", capital + "Type", slot);
                emitAddOffsetMethod(sb, accessor, capital, slot + 1);
                return slot + 2;
            }
            if (target instanceof Ast.TableDecl) {
                params.add("int " + accessor + "Offset");
                adds.add(new AddEntry("b.addOffset(" + slot + ", " + accessor + "Offset, 0);", 4, adds.size()));
                emitAddOffsetMethod(sb, accessor, capital, slot);
                return slot + 1;
            }
            if (target instanceof Ast.StructDecl s) {
                int align = registry.layoutOf(s).alignment();
                params.add("int " + accessor + "Offset");
                adds.add(new AddEntry("b.addStruct(" + slot + ", " + accessor + "Offset, 0);", align, adds.size()));
                return slot + 1;
            }
            // enum -> underlying scalar
            Ast.Scalar underlying = ((Ast.EnumDecl) target).underlying();
            emitScalarBuilderField(sb, accessor, capital, underlying, slot, field.defaultValue().orElse(null), params, adds);
            return slot + 1;
        }
        Ast.Scalar scalar = (Ast.Scalar) type;
        if (scalar == Ast.Scalar.STRING) {
            params.add("int " + accessor + "Offset");
            adds.add(new AddEntry("b.addOffset(" + slot + ", " + accessor + "Offset, 0);", 4, adds.size()));
            emitAddOffsetMethod(sb, accessor, capital, slot);
            return slot + 1;
        }
        emitScalarBuilderField(sb, accessor, capital, scalar, slot, field.defaultValue().orElse(null), params, adds);
        return slot + 1;
    }

    private void emitScalarBuilderField(StringBuilder sb, String accessor, String capital, Ast.Scalar scalar,
                                        int slot, String defaultValue, List<String> params, List<AddEntry> adds) {
        ScalarBuild sbuild = scalarBuild(scalar);
        String paramType = scalarIo(scalar).javaType;
        String def = buildDefault(sbuild.method, defaultValue);
        String value = sbuild.cast + accessor;
        params.add(paramType + " " + accessor);
        adds.add(new AddEntry("b." + sbuild.method + "(" + slot + ", " + value + ", " + def + ");", TypeRegistry.sizeOf(scalar), adds.size()));
        sb.append("""

                    /// Sets the `%1$s` field.
                    /// @param b the builder
                    /// @param %1$s value
                    public static void add%2$s(FbsBuilder b, %3$s %1$s) {
                        b.%4$s(%5$d, %6$s, %7$s);
                    }
                """.formatted(accessor, capital, paramType, sbuild.method, slot, value, def));
    }

    private void emitAddOffsetMethod(StringBuilder sb, String accessor, String capital, int slot) {
        sb.append("""

                    /// Sets the `%1$s` offset field.
                    /// @param b the builder
                    /// @param offset the referenced offset
                    public static void add%2$s(FbsBuilder b, int offset) {
                        b.addOffset(%3$d, offset, 0);
                    }
                """.formatted(accessor, capital, slot));
    }

    private void emitAddByteMethod(StringBuilder sb, String accessor, String capital, int slot) {
        sb.append("""

                    /// Sets the `%1$s` field.
                    /// @param b the builder
                    /// @param value the value
                    public static void add%2$s(FbsBuilder b, byte value) {
                        b.addByte(%3$d, value, 0);
                    }
                """.formatted(accessor, capital, slot));
    }

    private void emitVectorBuilders(StringBuilder sb, String accessor, String capital, Ast.FieldType element) {
        if (element instanceof Ast.Scalar scalar && (scalar == Ast.Scalar.UINT8 || scalar == Ast.Scalar.INT8)) {
            sb.append("""

                        /// Creates the `%1$s` byte vector.
                        /// @param b the builder
                        /// @param data the bytes
                        /// @return the vector offset
                        public static int create%2$sVector(FbsBuilder b, byte[] data) {
                            return b.createByteVector(data);
                        }
                    """.formatted(accessor, capital));
            emitStartVector(sb, accessor, capital, 1, 1);
            return;
        }
        if (element instanceof Ast.Scalar scalar && scalar != Ast.Scalar.STRING) {
            VectorElem ve = scalarVectorElem(scalar);
            sb.append("""

                        /// Creates the `%1$s` vector.
                        /// @param b the builder
                        /// @param data the elements
                        /// @return the vector offset
                        public static int create%2$sVector(FbsBuilder b, %3$s data) {
                            b.startVector(%4$d, data.length, %4$d);
                            for (int i = data.length - 1; i >= 0; i--) {
                                b.%5$s(%6$sdata[i]);
                            }
                            return b.endVector();
                        }
                    """.formatted(accessor, capital, ve.arrayType, ve.size, ve.add, ve.cast));
            emitStartVector(sb, accessor, capital, ve.size, ve.size);
            return;
        }
        // string or table-ref element -> offset vector; struct-ref element -> start only
        if (element instanceof Ast.Scalar || isOffsetElement(element)) {
            sb.append("""

                        /// Creates the `%1$s` offset vector.
                        /// @param b the builder
                        /// @param data element offsets
                        /// @return the vector offset
                        public static int create%2$sVector(FbsBuilder b, int[] data) {
                            b.startVector(4, data.length, 4);
                            for (int i = data.length - 1; i >= 0; i--) {
                                b.addOffset(data[i]);
                            }
                            return b.endVector();
                        }
                    """.formatted(accessor, capital));
            emitStartVector(sb, accessor, capital, 4, 4);
            return;
        }
        // struct element vector: only a start helper (elements written inline)
        TypeRegistry.StructLayout layout = registry.layoutOf((Ast.StructDecl) registry.resolve((Ast.Ref) element));
        emitStartVector(sb, accessor, capital, layout.size(), layout.alignment());
    }

    private boolean isOffsetElement(Ast.FieldType element) {
        return element instanceof Ast.Ref ref && registry.resolve(ref) instanceof Ast.TableDecl;
    }

    private void emitStartVector(StringBuilder sb, String accessor, String capital, int elemSize, int alignment) {
        sb.append("""

                    /// Begins the `%1$s` vector.
                    /// @param b the builder
                    /// @param numElems element count
                    public static void start%2$sVector(FbsBuilder b, int numElems) {
                        b.startVector(%3$d, numElems, %4$d);
                    }
                """.formatted(accessor, capital, elemSize, alignment));
    }

    // ---- struct builder -------------------------------------------------------

    private void emitStructBuilder(StringBuilder sb, Ast.StructDecl struct, TypeRegistry.StructLayout layout) {
        String name = className(struct.name());
        List<Ast.Field> fields = struct.fields();
        sb.append("\n    /// Writes an inline `").append(name).append("` struct.\n");
        sb.append("    /// @param b the builder\n");
        for (Ast.Field f : fields) {
            sb.append("    /// @param ").append(camelCase(f.name())).append(" field value\n");
        }
        sb.append("    /// @return the struct offset\n");
        sb.append("    public static int create").append(name).append("(FbsBuilder b");
        for (Ast.Field f : fields) {
            sb.append(", ").append(scalarIo(structFieldScalar(f)).javaType).append(" ").append(camelCase(f.name()));
        }
        sb.append(") {\n");
        sb.append("        b.prep(").append(layout.alignment()).append(", ").append(layout.size()).append(");\n");
        int cursor = layout.size();
        for (int i = fields.size() - 1; i >= 0; i--) {
            Ast.Field f = fields.get(i);
            Ast.Scalar scalar = structFieldScalar(f);
            int off = layout.fieldOffsets()[i];
            int gap = cursor - (off + TypeRegistry.sizeOf(scalar));
            if (gap > 0) {
                sb.append("        b.pad(").append(gap).append(");\n");
            }
            ScalarBuild sbuild = scalarBuild(scalar);
            sb.append("        b.").append(sbuild.put).append("(").append(sbuild.cast).append(camelCase(f.name())).append(");\n");
            cursor = off;
        }
        if (cursor > 0) {
            sb.append("        b.pad(").append(cursor).append(");\n");
        }
        sb.append("        return b.offset();\n    }\n");
    }

    private record ScalarBuild(String method, String put, String cast) {
    }

    private static ScalarBuild scalarBuild(Ast.Scalar scalar) {
        return switch (scalar) {
            case BOOL -> new ScalarBuild("addBoolean", "putByte", "");
            case INT8, UINT8 -> new ScalarBuild("addByte", "putByte", "(byte) ");
            case INT16, UINT16 -> new ScalarBuild("addShort", "putShort", "(short) ");
            case INT32 -> new ScalarBuild("addInt", "putInt", "");
            case UINT32 -> new ScalarBuild("addInt", "putInt", "(int) ");
            case INT64, UINT64 -> new ScalarBuild("addLong", "putLong", "");
            case FLOAT32 -> new ScalarBuild("addFloat", "putFloat", "");
            case FLOAT64 -> new ScalarBuild("addDouble", "putDouble", "");
            case STRING -> new ScalarBuild("addOffset", "putInt", "");
        };
    }

    /// Default literal for an `addX` builder call, typed to match the add method
    /// (e.g. `addInt` takes an `int` default even for an unsigned 32-bit field).
    private static String buildDefault(String addMethod, String defaultValue) {
        boolean has = defaultValue != null && !"null".equals(defaultValue);
        return switch (addMethod) {
            case "addBoolean" -> Boolean.toString("true".equals(defaultValue));
            case "addLong" -> (has ? defaultValue : "0") + "L";
            case "addFloat" -> (has ? defaultValue : "0") + "f";
            case "addDouble" -> has ? defaultValue : "0.0";
            default -> has ? defaultValue : "0";
        };
    }

    private record VectorElem(String arrayType, String add, String cast, int size) {
    }

    private static VectorElem scalarVectorElem(Ast.Scalar scalar) {
        return switch (scalar) {
            case INT16, UINT16 -> new VectorElem("int[]", "addShort", "(short) ", 2);
            case INT32 -> new VectorElem("int[]", "addInt", "", 4);
            case UINT32 -> new VectorElem("long[]", "addInt", "(int) ", 4);
            case INT64, UINT64 -> new VectorElem("long[]", "addLong", "", 8);
            case FLOAT32 -> new VectorElem("float[]", "addFloat", "", 4);
            case FLOAT64 -> new VectorElem("double[]", "addDouble", "", 8);
            default -> throw new FbsParseException("unsupported scalar vector element: " + scalar);
        };
    }

    // ---- scalar I/O model -----------------------------------------------------

    /// Read-expression model for one scalar. A read is composed structurally as
    /// `prefix + method(position) + suffix` (e.g. `(int) ` + `readShort(at)` + ``, or
    /// `readInt(at)` + ` & 0xFFFFFFFFL`), so the same scalar reads correctly at any
    /// position — table field (`pos + o`), vector element, or struct offset — without
    /// rewriting a literal string.
    ///
    /// @param javaType   accessor return type
    /// @param readPrefix expression prefix (e.g. a widening cast), or empty
    /// @param readMethod FbsTable/FbsMemorySegment reader method name
    /// @param readSuffix expression suffix (e.g. an unsigned mask or `!= 0`), or empty
    /// @param zero       default/absent value literal
    private record ScalarIo(String javaType, String readPrefix, String readMethod, String readSuffix, String zero) {
        /// @param at the absolute/relative byte-position expression to read at
        /// @return the read expression for that position
        String read(String at) {
            return readPrefix + readMethod + "(" + at + ")" + readSuffix;
        }

        String tableRead() {
            return read("pos + o");
        }

        String vectorRead(int size) {
            return "o != 0 ? " + read("vectorElements(o) + (long) j * " + size) + " : " + zero;
        }

        String structRead(int off) {
            return read(Integer.toString(off));
        }
    }

    private static ScalarIo scalarIo(Ast.Scalar scalar) {
        return switch (scalar) {
            case BOOL -> new ScalarIo("boolean", "", "readByte", " != 0", "false");
            case INT8 -> new ScalarIo("int", "(int) ", "readByte", "", "0");
            case UINT8 -> new ScalarIo("int", "", "readByte", " & 0xFF", "0");
            case INT16 -> new ScalarIo("int", "(int) ", "readShort", "", "0");
            case UINT16 -> new ScalarIo("int", "", "readShort", " & 0xFFFF", "0");
            case INT32 -> new ScalarIo("int", "", "readInt", "", "0");
            case UINT32 -> new ScalarIo("long", "", "readInt", " & 0xFFFFFFFFL", "0L");
            case INT64 -> new ScalarIo("long", "", "readLong", "", "0L");
            case UINT64 -> new ScalarIo("long", "", "readLong", "", "0L");
            case FLOAT32 -> new ScalarIo("float", "", "readFloat", "", "0.0f");
            case FLOAT64 -> new ScalarIo("double", "", "readDouble", "", "0.0");
            case STRING -> new ScalarIo("String", "", "readStringAt", "", "null");
        };
    }

    private static String defaultLiteral(ScalarIo io, String defaultValue) {
        if (defaultValue == null || "null".equals(defaultValue)) {
            return io.zero;
        }
        return switch (io.javaType) {
            case "long" -> defaultValue + "L";
            case "float" -> defaultValue + "f";
            default -> defaultValue;
        };
    }

    private static String enumConstType(Ast.Scalar underlying) {
        return switch (TypeRegistry.sizeOf(underlying)) {
            case 1 -> "byte";
            case 2 -> "short";
            case 8 -> "long";
            default -> "int";
        };
    }

    private static String literal(String constType, long value) {
        return switch (constType) {
            case "byte" -> "(byte) " + value;
            case "short" -> "(short) " + value;
            case "long" -> value + "L";
            default -> Long.toString(value);
        };
    }

    private static String simpleName(String qualified) {
        int dot = qualified.lastIndexOf('.');
        return dot >= 0 ? qualified.substring(dot + 1) : qualified;
    }

    private static String camelCase(String snake) {
        StringBuilder sb = new StringBuilder();
        boolean upper = false;
        for (int i = 0; i < snake.length(); i++) {
            char c = snake.charAt(i);
            if (c == '_') {
                upper = sb.length() > 0;
            } else if (upper) {
                sb.append(Character.toUpperCase(c));
                upper = false;
            } else {
                sb.append(c);
            }
        }
        return sb.isEmpty() ? snake : sb.toString();
    }

    private static String capitalize(String s) {
        return s.isEmpty() ? s : Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }
}
