package io.github.dfa1.vortex.fbsgen;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/// Emits MemorySegment-native FlatBuffers reader/builder classes from a [TypeRegistry].
///
/// One `.java` file per declaration:
/// - each `table` becomes a `final class extends FbsTable` with read accessors plus
///   `createX`/`startX`/`addX`/`endX`/`finishXBuffer` builders;
/// - each `struct` becomes a `final class extends FbsStruct` with inline-offset accessors
///   and an inline `createX` builder;
/// - each `enum` becomes a constants holder over its underlying integer type;
/// - each `union` becomes a discriminator-constants holder (NONE = 0, members from 1).
///
/// The wire layout is the standard FlatBuffers binary format — see [FbsTable]/[FbsBuilder].
public final class CodeGen {

    private static final String RUNTIME_PACKAGE = "io.github.dfa1.vortex.fbsrt";

    /// Prefix applied to every emitted Java class name so the generated wire-format
    /// classes (`Array`, `DType`, `Bool`, `List`, …) do not collide with project or JDK
    /// types of the same name. Schema files keep the upstream (unprefixed) names; the
    /// prefix lives here, mirroring proto-gen's `JAVA_NAME_PREFIX`.
    private static final String JAVA_NAME_PREFIX = "Fbs";

    private static final String GENERATED_ANNOTATION = "@Generated(\"io.github.dfa1.vortex.fbsgen.CodeGen\")\n";

    private final TypeRegistry registry;

    /// @param registry resolved schema model
    public CodeGen(TypeRegistry registry) {
        this.registry = registry;
    }

    /// Emits every declaration to `outDir`, one file per type.
    ///
    /// @param outDir output directory (the package directory)
    /// @throws IOException on filesystem errors
    public void emit(Path outDir) throws IOException {
        Files.createDirectories(outDir);
        for (Ast.Decl decl : registry.all()) {
            String src = switch (decl) {
                case Ast.TableDecl t -> emitTable(t);
                case Ast.StructDecl s -> emitStruct(s);
                case Ast.EnumDecl e -> emitEnum(e);
                case Ast.UnionDecl u -> emitUnion(u);
            };
            Files.writeString(outDir.resolve(className(decl.name()) + ".java"), src);
        }
    }

    private String preamble(String importBlock) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by vortex-fbs-gen. Do not edit.\n\n");
        sb.append("package ").append(registry.javaPackage()).append(";\n\n");
        sb.append(importBlock);
        sb.append("import javax.annotation.processing.Generated;\n\n");
        return sb.toString();
    }

    /// Maps a schema type name to its generated Java class name (prefixed).
    ///
    /// @param schemaName the name as written in the `.fbs` schema
    /// @return the Java class name
    private static String className(String schemaName) {
        return JAVA_NAME_PREFIX + schemaName;
    }

    // ---- tables ---------------------------------------------------------------

    private String emitTable(Ast.TableDecl table) {
        String name = className(table.name());
        StringBuilder sb = new StringBuilder();
        sb.append(preamble("import " + RUNTIME_PACKAGE + ".FbsBuilder;\nimport " + RUNTIME_PACKAGE
                + ".FbsTable;\nimport java.lang.foreign.MemorySegment;\n"));
        sb.append("/// Reader and builder for the `").append(table.name()).append("` FlatBuffers table.\n");
        sb.append(GENERATED_ANNOTATION);
        sb.append("public final class ").append(name).append(" extends FbsTable {\n\n");

        sb.append("    /// Positions a reader at the root table of a finished buffer.\n");
        sb.append("    /// @param seg the buffer\n");
        sb.append("    /// @return a reader positioned at the root\n");
        sb.append("    public static ").append(name).append(" getRootAs").append(name)
                .append("(MemorySegment seg) {\n");
        sb.append("        return new ").append(name).append("().assign(seg, FbsTable.rootPosition(seg, 0));\n");
        sb.append("    }\n\n");

        sb.append("    /// Positions this reader at a table.\n");
        sb.append("    /// @param seg the buffer\n");
        sb.append("    /// @param position the table position\n");
        sb.append("    /// @return this\n");
        sb.append("    public ").append(name).append(" assign(MemorySegment seg, long position) {\n");
        sb.append("        init(seg, position);\n");
        sb.append("        return this;\n");
        sb.append("    }\n");

        int vtableIndex = 0;
        for (Ast.Field field : table.fields()) {
            vtableIndex = emitTableField(sb, field, vtableIndex);
        }
        emitTableBuilder(sb, table);
        sb.append("}\n");
        return sb.toString();
    }

    /// Emits accessors for one table field; returns the next vtable index (a union
    /// consumes two slots: discriminator + value).
    private int emitTableField(StringBuilder sb, Ast.Field field, int vtableIndex) {
        String accessor = camelCase(field.name());
        Ast.FieldType type = field.type();
        int vt = 4 + vtableIndex * 2;

        if (type instanceof Ast.Scalar scalar) {
            emitScalarTableField(sb, accessor, scalar, vt, field.defaultValue().orElse(null));
            return vtableIndex + 1;
        }
        if (type instanceof Ast.Vector vector) {
            emitVectorField(sb, accessor, vector.element(), vt);
            return vtableIndex + 1;
        }
        Ast.Ref ref = (Ast.Ref) type;
        Ast.Decl target = registry.resolve(ref);
        return switch (target) {
            case Ast.EnumDecl e -> {
                emitScalarTableField(sb, accessor, e.underlying(), vt, field.defaultValue().orElse(null));
                yield vtableIndex + 1;
            }
            case Ast.UnionDecl u -> {
                emitUnionField(sb, accessor, vt);
                yield vtableIndex + 2;
            }
            case Ast.TableDecl t -> {
                emitObjectField(sb, accessor, className(t.name()), vt, true);
                yield vtableIndex + 1;
            }
            case Ast.StructDecl s -> {
                emitObjectField(sb, accessor, className(s.name()), vt, false);
                yield vtableIndex + 1;
            }
        };
    }

    private void emitScalarTableField(StringBuilder sb, String accessor, Ast.Scalar scalar, int vt, String defaultValue) {
        ScalarIo io = scalarIo(scalar);
        String read = io.tableRead();
        sb.append("\n    /// @return the `").append(accessor).append("` field\n");
        if (scalar == Ast.Scalar.BOOL) {
            boolean def = "true".equals(defaultValue);
            sb.append("    public boolean ").append(accessor).append("() {\n");
            sb.append("        int o = fieldOffset(").append(vt).append(");\n");
            sb.append("        return o != 0 ? readByte(pos + o) != 0 : ").append(def).append(";\n");
            sb.append("    }\n");
        } else {
            String def = defaultLiteral(io, defaultValue);
            sb.append("    public ").append(io.javaType).append(" ").append(accessor).append("() {\n");
            sb.append("        int o = fieldOffset(").append(vt).append(");\n");
            sb.append("        return o != 0 ? ").append(read).append(" : ").append(def).append(";\n");
            sb.append("    }\n");
        }
        if ("null".equals(defaultValue)) {
            sb.append("\n    /// @return whether the optional `").append(accessor).append("` field is present\n");
            sb.append("    public boolean has").append(capitalize(accessor)).append("() {\n");
            sb.append("        return fieldOffset(").append(vt).append(") != 0;\n");
            sb.append("    }\n");
        }
    }

    private void emitObjectField(StringBuilder sb, String accessor, String typeName, int vt, boolean indirect) {
        String target = indirect ? "indirect(pos + o)" : "pos + o";
        sb.append("\n    /// @return the `").append(accessor).append("` child, or null if absent\n");
        sb.append("    public ").append(typeName).append(" ").append(accessor).append("() {\n");
        sb.append("        int o = fieldOffset(").append(vt).append(");\n");
        sb.append("        return o != 0 ? new ").append(typeName).append("().assign(seg, ").append(target).append(") : null;\n");
        sb.append("    }\n");
    }

    private void emitUnionField(StringBuilder sb, String accessor, int vtType) {
        int vtValue = vtType + 2;
        sb.append("\n    /// @return the union discriminator for `").append(accessor).append("` (0 = none)\n");
        sb.append("    public int ").append(accessor).append("Type() {\n");
        sb.append("        int o = fieldOffset(").append(vtType).append(");\n");
        sb.append("        return o != 0 ? readByte(pos + o) & 0xFF : 0;\n");
        sb.append("    }\n");
        sb.append("\n    /// Projects the selected `").append(accessor).append("` member onto the given reader.\n");
        sb.append("    /// @param obj a reader for the expected member type\n");
        sb.append("    /// @param <T> the member reader type\n");
        sb.append("    /// @return the positioned reader, or null if the union is absent\n");
        sb.append("    public <T extends FbsTable> T ").append(accessor).append("(T obj) {\n");
        sb.append("        int o = fieldOffset(").append(vtValue).append(");\n");
        sb.append("        return o != 0 ? locate(obj, unionMemberPosition(o)) : null;\n");
        sb.append("    }\n");
    }

    private void emitVectorField(StringBuilder sb, String accessor, Ast.FieldType element, int vt) {
        sb.append("\n    /// @return the length of the `").append(accessor).append("` vector\n");
        sb.append("    public int ").append(accessor).append("Length() {\n");
        sb.append("        int o = fieldOffset(").append(vt).append(");\n");
        sb.append("        return o != 0 ? vectorLength(o) : 0;\n");
        sb.append("    }\n");

        if (element instanceof Ast.Scalar scalar) {
            emitScalarVectorElements(sb, accessor, scalar, vt);
            return;
        }
        Ast.Ref ref = (Ast.Ref) element;
        Ast.Decl target = registry.resolve(ref);
        switch (target) {
            case Ast.EnumDecl e -> emitScalarVectorElements(sb, accessor, e.underlying(), vt);
            case Ast.TableDecl t -> emitObjectVectorElement(sb, accessor, className(t.name()), vt, 4, true);
            case Ast.StructDecl s -> emitObjectVectorElement(sb, accessor, className(s.name()), vt, registry.layoutOf(s).size(), false);
            case Ast.UnionDecl u -> throw new FbsParseException("vectors of unions are not supported ('" + accessor + "')");
        }
    }

    private void emitScalarVectorElements(StringBuilder sb, String accessor, Ast.Scalar scalar, int vt) {
        if (scalar == Ast.Scalar.STRING) {
            sb.append("\n    /// @param j element index\n    /// @return the j-th `").append(accessor).append("` string\n");
            sb.append("    public String ").append(accessor).append("(int j) {\n");
            sb.append("        int o = fieldOffset(").append(vt).append(");\n");
            sb.append("        return readStringAt(vectorElements(o) + (long) j * 4);\n");
            sb.append("    }\n");
            return;
        }
        ScalarIo io = scalarIo(scalar);
        int size = TypeRegistry.sizeOf(scalar);
        sb.append("\n    /// @param j element index\n    /// @return the j-th `").append(accessor).append("` element\n");
        sb.append("    public ").append(io.javaType).append(" ").append(accessor).append("(int j) {\n");
        sb.append("        int o = fieldOffset(").append(vt).append(");\n");
        sb.append("        return ").append(io.vectorRead(size)).append(";\n");
        sb.append("    }\n");
        if (scalar == Ast.Scalar.UINT8 || scalar == Ast.Scalar.INT8) {
            sb.append("\n    /// @return a zero-copy slice of the `").append(accessor).append("` byte vector, or null if absent\n");
            sb.append("    public MemorySegment ").append(accessor).append("AsSegment() {\n");
            sb.append("        int o = fieldOffset(").append(vt).append(");\n");
            sb.append("        return o != 0 ? byteVector(o) : null;\n");
            sb.append("    }\n");
        }
    }

    private void emitObjectVectorElement(StringBuilder sb, String accessor, String typeName, int vt, int stride, boolean indirect) {
        String base = "vectorElements(o) + (long) j * " + stride;
        String target = indirect ? "indirect(" + base + ")" : base;
        sb.append("\n    /// @param j element index\n    /// @return the j-th `").append(accessor).append("` element\n");
        sb.append("    public ").append(typeName).append(" ").append(accessor).append("(int j) {\n");
        sb.append("        int o = fieldOffset(").append(vt).append(");\n");
        sb.append("        return new ").append(typeName).append("().assign(seg, ").append(target).append(");\n");
        sb.append("    }\n");
    }

    // ---- structs --------------------------------------------------------------

    private String emitStruct(Ast.StructDecl struct) {
        String name = className(struct.name());
        TypeRegistry.StructLayout layout = registry.layoutOf(struct);
        StringBuilder sb = new StringBuilder();
        sb.append(preamble("import " + RUNTIME_PACKAGE + ".FbsBuilder;\nimport " + RUNTIME_PACKAGE
                + ".FbsStruct;\nimport java.lang.foreign.MemorySegment;\n"));
        sb.append("/// Reader and builder for the `").append(struct.name()).append("` FlatBuffers struct (inline, ")
                .append(layout.size()).append(" bytes).\n");
        sb.append(GENERATED_ANNOTATION);
        sb.append("public final class ").append(name).append(" extends FbsStruct {\n\n");
        sb.append("    /// Positions this reader at a struct.\n");
        sb.append("    /// @param seg the buffer\n");
        sb.append("    /// @param position the struct position\n");
        sb.append("    /// @return this\n");
        sb.append("    public ").append(name).append(" assign(MemorySegment seg, long position) {\n");
        sb.append("        init(seg, position);\n");
        sb.append("        return this;\n");
        sb.append("    }\n");

        for (int i = 0; i < struct.fields().size(); i++) {
            Ast.Field field = struct.fields().get(i);
            int off = layout.fieldOffsets()[i];
            Ast.Scalar scalar = structFieldScalar(field);
            emitScalarStructField(sb, camelCase(field.name()), scalar, off);
        }
        emitStructBuilder(sb, struct, layout);
        sb.append("}\n");
        return sb.toString();
    }

    private Ast.Scalar structFieldScalar(Ast.Field field) {
        if (field.type() instanceof Ast.Scalar s) {
            return s;
        }
        return ((Ast.EnumDecl) registry.resolve((Ast.Ref) field.type())).underlying();
    }

    private void emitScalarStructField(StringBuilder sb, String accessor, Ast.Scalar scalar, int off) {
        ScalarIo io = scalarIo(scalar);
        sb.append("\n    /// @return the `").append(accessor).append("` field\n");
        if (scalar == Ast.Scalar.BOOL) {
            sb.append("    public boolean ").append(accessor).append("() {\n");
            sb.append("        return readByte(").append(off).append(") != 0;\n");
            sb.append("    }\n");
        } else {
            sb.append("    public ").append(io.javaType).append(" ").append(accessor).append("() {\n");
            sb.append("        return ").append(io.structRead(off)).append(";\n");
            sb.append("    }\n");
        }
    }

    // ---- enums & unions -------------------------------------------------------

    private String emitEnum(Ast.EnumDecl e) {
        String constType = enumConstType(e.underlying());
        StringBuilder sb = new StringBuilder();
        String name = className(e.name());
        sb.append(preamble(""));
        sb.append("/// Constants for the `").append(e.name()).append("` FlatBuffers enum.\n");
        sb.append(GENERATED_ANNOTATION);
        sb.append("public final class ").append(name).append(" {\n\n");
        sb.append("    private ").append(name).append("() {\n    }\n");
        long next = 0;
        for (Ast.EnumVal v : e.values()) {
            long value = v.number().isPresent() ? v.number().getAsInt() : next;
            next = value + 1;
            sb.append("\n    /// `").append(v.name()).append("` = ").append(value).append("\n");
            sb.append("    public static final ").append(constType).append(" ").append(v.name())
                    .append(" = ").append(literal(constType, value)).append(";\n");
        }
        sb.append("}\n");
        return sb.toString();
    }

    private String emitUnion(Ast.UnionDecl u) {
        StringBuilder sb = new StringBuilder();
        String name = className(u.name());
        sb.append(preamble(""));
        sb.append("/// Discriminator constants for the `").append(u.name()).append("` FlatBuffers union.\n");
        sb.append(GENERATED_ANNOTATION);
        sb.append("public final class ").append(name).append(" {\n\n");
        sb.append("    private ").append(name).append("() {\n    }\n");
        sb.append("\n    /// No member selected.\n");
        sb.append("    public static final byte NONE = 0;\n");
        long next = 1;
        for (Ast.UnionMember m : u.members()) {
            long value = m.number().isPresent() ? m.number().getAsInt() : next;
            next = value + 1;
            String member = className(simpleName(m.typeName()));
            sb.append("\n    /// Member `").append(simpleName(m.typeName())).append("` = ").append(value).append("\n");
            sb.append("    public static final byte ").append(member).append(" = ").append(literal("byte", value)).append(";\n");
        }
        sb.append("}\n");
        return sb.toString();
    }

    // ---- table builders -------------------------------------------------------

    private void emitTableBuilder(StringBuilder sb, Ast.TableDecl table) {
        String name = className(table.name());
        List<String> params = new ArrayList<>();
        List<AddEntry> adds = new ArrayList<>();
        int slots = 0;
        for (Ast.Field field : table.fields()) {
            slots = collectBuilderField(sb, field, slots, params, adds);
        }
        // Match flatc's createX ordering: add fields by descending alignment, and within
        // an alignment group in reverse declaration order. This keeps the data region gap-free
        // and makes our output byte-identical to flatc.
        //
        // Limitation: an inline struct field (addStruct) must be the most-recently-written
        // object when it is slotted (FbsBuilder.addStruct enforces x == offset()). This holds
        // for vortex today because structs (Buffer, SegmentSpec) only ever appear as VECTOR
        // elements, never as inline table fields. If a future schema adds an inline struct
        // field that shares an alignment group with a scalar sorted ahead of it, this ordering
        // could place the scalar between the struct write and its slot and trip that guard.
        // Revisit the ordering (emit struct fields last within their group) if that ever lands.
        adds.sort((x, y) -> x.align != y.align ? Integer.compare(y.align, x.align) : Integer.compare(y.order, x.order));

        sb.append("\n    /// Builds a `").append(name).append("` table.\n");
        sb.append("    /// @param b the builder\n");
        for (String p : params) {
            sb.append("    /// @param ").append(p.substring(p.indexOf(' ') + 1)).append(" field value\n");
        }
        sb.append("    /// @return the table offset\n");
        sb.append("    public static int create").append(name).append("(FbsBuilder b");
        for (String p : params) {
            sb.append(", ").append(p);
        }
        sb.append(") {\n");
        sb.append("        b.startTable(").append(slots).append(");\n");
        for (AddEntry add : adds) {
            sb.append("        ").append(add.statement).append("\n");
        }
        sb.append("        return b.endTable();\n    }\n");

        sb.append("\n    /// Begins a `").append(name).append("` table.\n");
        sb.append("    /// @param b the builder\n");
        sb.append("    public static void start").append(name).append("(FbsBuilder b) {\n");
        sb.append("        b.startTable(").append(slots).append(");\n    }\n");

        sb.append("\n    /// Finishes a `").append(name).append("` table.\n");
        sb.append("    /// @param b the builder\n    /// @return the table offset\n");
        sb.append("    public static int end").append(name).append("(FbsBuilder b) {\n");
        sb.append("        return b.endTable();\n    }\n");

        sb.append("\n    /// Finishes the buffer with a `").append(name).append("` root.\n");
        sb.append("    /// @param b the builder\n    /// @param offset the root table offset\n");
        sb.append("    public static void finish").append(name).append("Buffer(FbsBuilder b, int offset) {\n");
        sb.append("        b.finish(offset);\n    }\n");
    }

    /// One add-call emitted inside `createX`, tagged with its alignment and declaration
    /// order so the calls can be reordered to match flatc.
    private record AddEntry(String statement, int align, int order) {
    }

    /// Emits per-field `add*` methods (and vector helpers), and records the createX
    /// parameter list and add-call list; returns the next slot index.
    private int collectBuilderField(StringBuilder sb, Ast.Field field, int slot, List<String> params, List<AddEntry> adds) {
        String accessor = camelCase(field.name());
        String capital = capitalize(accessor);
        Ast.FieldType type = field.type();

        if (type instanceof Ast.Vector vector) {
            params.add("int " + accessor + "Offset");
            adds.add(new AddEntry("b.addOffset(" + slot + ", " + accessor + "Offset, 0);", 4, adds.size()));
            emitAddOffsetMethod(sb, accessor, capital, slot);
            emitVectorBuilders(sb, accessor, capital, vector.element());
            return slot + 1;
        }
        if (type instanceof Ast.Ref ref) {
            Ast.Decl target = registry.resolve(ref);
            if (target instanceof Ast.UnionDecl) {
                params.add("byte " + accessor + "Type");
                params.add("int " + accessor + "Offset");
                adds.add(new AddEntry("b.addByte(" + slot + ", " + accessor + "Type, 0);", 1, adds.size()));
                adds.add(new AddEntry("b.addOffset(" + (slot + 1) + ", " + accessor + "Offset, 0);", 4, adds.size()));
                emitAddByteMethod(sb, accessor + "Type", capital + "Type", slot);
                emitAddOffsetMethod(sb, accessor, capital, slot + 1);
                return slot + 2;
            }
            if (target instanceof Ast.TableDecl) {
                params.add("int " + accessor + "Offset");
                adds.add(new AddEntry("b.addOffset(" + slot + ", " + accessor + "Offset, 0);", 4, adds.size()));
                emitAddOffsetMethod(sb, accessor, capital, slot);
                return slot + 1;
            }
            if (target instanceof Ast.StructDecl s) {
                int align = registry.layoutOf(s).alignment();
                params.add("int " + accessor + "Offset");
                adds.add(new AddEntry("b.addStruct(" + slot + ", " + accessor + "Offset, 0);", align, adds.size()));
                return slot + 1;
            }
            // enum -> underlying scalar
            Ast.Scalar underlying = ((Ast.EnumDecl) target).underlying();
            emitScalarBuilderField(sb, accessor, capital, underlying, slot, field.defaultValue().orElse(null), params, adds);
            return slot + 1;
        }
        Ast.Scalar scalar = (Ast.Scalar) type;
        if (scalar == Ast.Scalar.STRING) {
            params.add("int " + accessor + "Offset");
            adds.add(new AddEntry("b.addOffset(" + slot + ", " + accessor + "Offset, 0);", 4, adds.size()));
            emitAddOffsetMethod(sb, accessor, capital, slot);
            return slot + 1;
        }
        emitScalarBuilderField(sb, accessor, capital, scalar, slot, field.defaultValue().orElse(null), params, adds);
        return slot + 1;
    }

    private void emitScalarBuilderField(StringBuilder sb, String accessor, String capital, Ast.Scalar scalar,
                                        int slot, String defaultValue, List<String> params, List<AddEntry> adds) {
        ScalarBuild sbuild = scalarBuild(scalar);
        String paramType = scalarIo(scalar).javaType;
        String def = buildDefault(sbuild.method, defaultValue);
        String value = sbuild.cast + accessor;
        params.add(paramType + " " + accessor);
        adds.add(new AddEntry("b." + sbuild.method + "(" + slot + ", " + value + ", " + def + ");", TypeRegistry.sizeOf(scalar), adds.size()));
        sb.append("\n    /// Sets the `").append(accessor).append("` field.\n");
        sb.append("    /// @param b the builder\n    /// @param ").append(accessor).append(" value\n");
        sb.append("    public static void add").append(capital).append("(FbsBuilder b, ").append(paramType)
                .append(" ").append(accessor).append(") {\n");
        sb.append("        b.").append(sbuild.method).append("(").append(slot).append(", ").append(value)
                .append(", ").append(def).append(");\n    }\n");
    }

    private void emitAddOffsetMethod(StringBuilder sb, String accessor, String capital, int slot) {
        sb.append("\n    /// Sets the `").append(accessor).append("` offset field.\n");
        sb.append("    /// @param b the builder\n    /// @param offset the referenced offset\n");
        sb.append("    public static void add").append(capital).append("(FbsBuilder b, int offset) {\n");
        sb.append("        b.addOffset(").append(slot).append(", offset, 0);\n    }\n");
    }

    private void emitAddByteMethod(StringBuilder sb, String accessor, String capital, int slot) {
        sb.append("\n    /// Sets the `").append(accessor).append("` field.\n");
        sb.append("    /// @param b the builder\n    /// @param value the value\n");
        sb.append("    public static void add").append(capital).append("(FbsBuilder b, byte value) {\n");
        sb.append("        b.addByte(").append(slot).append(", value, 0);\n    }\n");
    }

    private void emitVectorBuilders(StringBuilder sb, String accessor, String capital, Ast.FieldType element) {
        if (element instanceof Ast.Scalar scalar && (scalar == Ast.Scalar.UINT8 || scalar == Ast.Scalar.INT8)) {
            sb.append("\n    /// Creates the `").append(accessor).append("` byte vector.\n");
            sb.append("    /// @param b the builder\n    /// @param data the bytes\n    /// @return the vector offset\n");
            sb.append("    public static int create").append(capital).append("Vector(FbsBuilder b, byte[] data) {\n");
            sb.append("        return b.createByteVector(data);\n    }\n");
            emitStartVector(sb, accessor, capital, 1, 1);
            return;
        }
        if (element instanceof Ast.Scalar scalar && scalar != Ast.Scalar.STRING) {
            VectorElem ve = scalarVectorElem(scalar);
            sb.append("\n    /// Creates the `").append(accessor).append("` vector.\n");
            sb.append("    /// @param b the builder\n    /// @param data the elements\n    /// @return the vector offset\n");
            sb.append("    public static int create").append(capital).append("Vector(FbsBuilder b, ").append(ve.arrayType).append(" data) {\n");
            sb.append("        b.startVector(").append(ve.size).append(", data.length, ").append(ve.size).append(");\n");
            sb.append("        for (int i = data.length - 1; i >= 0; i--) {\n");
            sb.append("            b.").append(ve.add).append("(").append(ve.cast).append("data[i]);\n        }\n");
            sb.append("        return b.endVector();\n    }\n");
            emitStartVector(sb, accessor, capital, ve.size, ve.size);
            return;
        }
        // string or table-ref element -> offset vector; struct-ref element -> start only
        if (element instanceof Ast.Scalar || isOffsetElement(element)) {
            sb.append("\n    /// Creates the `").append(accessor).append("` offset vector.\n");
            sb.append("    /// @param b the builder\n    /// @param data element offsets\n    /// @return the vector offset\n");
            sb.append("    public static int create").append(capital).append("Vector(FbsBuilder b, int[] data) {\n");
            sb.append("        b.startVector(4, data.length, 4);\n");
            sb.append("        for (int i = data.length - 1; i >= 0; i--) {\n");
            sb.append("            b.addOffset(data[i]);\n        }\n");
            sb.append("        return b.endVector();\n    }\n");
            emitStartVector(sb, accessor, capital, 4, 4);
            return;
        }
        // struct element vector: only a start helper (elements written inline)
        TypeRegistry.StructLayout layout = registry.layoutOf((Ast.StructDecl) registry.resolve((Ast.Ref) element));
        emitStartVector(sb, accessor, capital, layout.size(), layout.alignment());
    }

    private boolean isOffsetElement(Ast.FieldType element) {
        return element instanceof Ast.Ref ref && registry.resolve(ref) instanceof Ast.TableDecl;
    }

    private void emitStartVector(StringBuilder sb, String accessor, String capital, int elemSize, int alignment) {
        sb.append("\n    /// Begins the `").append(accessor).append("` vector.\n");
        sb.append("    /// @param b the builder\n    /// @param numElems element count\n");
        sb.append("    public static void start").append(capital).append("Vector(FbsBuilder b, int numElems) {\n");
        sb.append("        b.startVector(").append(elemSize).append(", numElems, ").append(alignment).append(");\n    }\n");
    }

    // ---- struct builder -------------------------------------------------------

    private void emitStructBuilder(StringBuilder sb, Ast.StructDecl struct, TypeRegistry.StructLayout layout) {
        String name = className(struct.name());
        List<Ast.Field> fields = struct.fields();
        sb.append("\n    /// Writes an inline `").append(name).append("` struct.\n");
        sb.append("    /// @param b the builder\n");
        for (Ast.Field f : fields) {
            sb.append("    /// @param ").append(camelCase(f.name())).append(" field value\n");
        }
        sb.append("    /// @return the struct offset\n");
        sb.append("    public static int create").append(name).append("(FbsBuilder b");
        for (Ast.Field f : fields) {
            sb.append(", ").append(scalarIo(structFieldScalar(f)).javaType).append(" ").append(camelCase(f.name()));
        }
        sb.append(") {\n");
        sb.append("        b.prep(").append(layout.alignment()).append(", ").append(layout.size()).append(");\n");
        int cursor = layout.size();
        for (int i = fields.size() - 1; i >= 0; i--) {
            Ast.Field f = fields.get(i);
            Ast.Scalar scalar = structFieldScalar(f);
            int off = layout.fieldOffsets()[i];
            int gap = cursor - (off + TypeRegistry.sizeOf(scalar));
            if (gap > 0) {
                sb.append("        b.pad(").append(gap).append(");\n");
            }
            ScalarBuild sbuild = scalarBuild(scalar);
            sb.append("        b.").append(sbuild.put).append("(").append(sbuild.cast).append(camelCase(f.name())).append(");\n");
            cursor = off;
        }
        if (cursor > 0) {
            sb.append("        b.pad(").append(cursor).append(");\n");
        }
        sb.append("        return b.offset();\n    }\n");
    }

    private record ScalarBuild(String method, String put, String cast) {
    }

    private static ScalarBuild scalarBuild(Ast.Scalar scalar) {
        return switch (scalar) {
            case BOOL -> new ScalarBuild("addBoolean", "putByte", "");
            case INT8, UINT8 -> new ScalarBuild("addByte", "putByte", "(byte) ");
            case INT16, UINT16 -> new ScalarBuild("addShort", "putShort", "(short) ");
            case INT32 -> new ScalarBuild("addInt", "putInt", "");
            case UINT32 -> new ScalarBuild("addInt", "putInt", "(int) ");
            case INT64, UINT64 -> new ScalarBuild("addLong", "putLong", "");
            case FLOAT32 -> new ScalarBuild("addFloat", "putFloat", "");
            case FLOAT64 -> new ScalarBuild("addDouble", "putDouble", "");
            case STRING -> new ScalarBuild("addOffset", "putInt", "");
        };
    }

    /// Default literal for an `addX` builder call, typed to match the add method
    /// (e.g. `addInt` takes an `int` default even for an unsigned 32-bit field).
    private static String buildDefault(String addMethod, String defaultValue) {
        boolean has = defaultValue != null && !"null".equals(defaultValue);
        return switch (addMethod) {
            case "addBoolean" -> Boolean.toString("true".equals(defaultValue));
            case "addLong" -> (has ? defaultValue : "0") + "L";
            case "addFloat" -> (has ? defaultValue : "0") + "f";
            case "addDouble" -> has ? defaultValue : "0.0";
            default -> has ? defaultValue : "0";
        };
    }

    private record VectorElem(String arrayType, String add, String cast, int size) {
    }

    private static VectorElem scalarVectorElem(Ast.Scalar scalar) {
        return switch (scalar) {
            case INT16, UINT16 -> new VectorElem("int[]", "addShort", "(short) ", 2);
            case INT32 -> new VectorElem("int[]", "addInt", "", 4);
            case UINT32 -> new VectorElem("long[]", "addInt", "(int) ", 4);
            case INT64, UINT64 -> new VectorElem("long[]", "addLong", "", 8);
            case FLOAT32 -> new VectorElem("float[]", "addFloat", "", 4);
            case FLOAT64 -> new VectorElem("double[]", "addDouble", "", 8);
            default -> throw new FbsParseException("unsupported scalar vector element: " + scalar);
        };
    }

    // ---- scalar I/O model -----------------------------------------------------

    /// Read-expression model for one scalar. A read is composed structurally as
    /// `prefix + method(position) + suffix` (e.g. `(int) ` + `readShort(at)` + ``, or
    /// `readInt(at)` + ` & 0xFFFFFFFFL`), so the same scalar reads correctly at any
    /// position — table field (`pos + o`), vector element, or struct offset — without
    /// rewriting a literal string.
    ///
    /// @param javaType   accessor return type
    /// @param readPrefix expression prefix (e.g. a widening cast), or empty
    /// @param readMethod FbsTable/FbsStruct reader method name
    /// @param readSuffix expression suffix (e.g. an unsigned mask or `!= 0`), or empty
    /// @param zero       default/absent value literal
    private record ScalarIo(String javaType, String readPrefix, String readMethod, String readSuffix, String zero) {
        /// @param at the absolute/relative byte-position expression to read at
        /// @return the read expression for that position
        String read(String at) {
            return readPrefix + readMethod + "(" + at + ")" + readSuffix;
        }

        String tableRead() {
            return read("pos + o");
        }

        String vectorRead(int size) {
            return "o != 0 ? " + read("vectorElements(o) + (long) j * " + size) + " : " + zero;
        }

        String structRead(int off) {
            return read(Integer.toString(off));
        }
    }

    private static ScalarIo scalarIo(Ast.Scalar scalar) {
        return switch (scalar) {
            case BOOL -> new ScalarIo("boolean", "", "readByte", " != 0", "false");
            case INT8 -> new ScalarIo("int", "(int) ", "readByte", "", "0");
            case UINT8 -> new ScalarIo("int", "", "readByte", " & 0xFF", "0");
            case INT16 -> new ScalarIo("int", "(int) ", "readShort", "", "0");
            case UINT16 -> new ScalarIo("int", "", "readShort", " & 0xFFFF", "0");
            case INT32 -> new ScalarIo("int", "", "readInt", "", "0");
            case UINT32 -> new ScalarIo("long", "", "readInt", " & 0xFFFFFFFFL", "0L");
            case INT64 -> new ScalarIo("long", "", "readLong", "", "0L");
            case UINT64 -> new ScalarIo("long", "", "readLong", "", "0L");
            case FLOAT32 -> new ScalarIo("float", "", "readFloat", "", "0.0f");
            case FLOAT64 -> new ScalarIo("double", "", "readDouble", "", "0.0");
            case STRING -> new ScalarIo("String", "", "readStringAt", "", "null");
        };
    }

    private static String defaultLiteral(ScalarIo io, String defaultValue) {
        if (defaultValue == null || "null".equals(defaultValue)) {
            return io.zero;
        }
        return switch (io.javaType) {
            case "long" -> defaultValue + "L";
            case "float" -> defaultValue + "f";
            default -> defaultValue;
        };
    }

    private static String enumConstType(Ast.Scalar underlying) {
        return switch (TypeRegistry.sizeOf(underlying)) {
            case 1 -> "byte";
            case 2 -> "short";
            case 8 -> "long";
            default -> "int";
        };
    }

    private static String literal(String constType, long value) {
        return switch (constType) {
            case "byte" -> "(byte) " + value;
            case "short" -> "(short) " + value;
            case "long" -> value + "L";
            default -> Long.toString(value);
        };
    }

    private static String simpleName(String qualified) {
        int dot = qualified.lastIndexOf('.');
        return dot >= 0 ? qualified.substring(dot + 1) : qualified;
    }

    private static String camelCase(String snake) {
        StringBuilder sb = new StringBuilder();
        boolean upper = false;
        for (int i = 0; i < snake.length(); i++) {
            char c = snake.charAt(i);
            if (c == '_') {
                upper = sb.length() > 0;
            } else if (upper) {
                sb.append(Character.toUpperCase(c));
                upper = false;
            } else {
                sb.append(c);
            }
        }
        return sb.isEmpty() ? snake : sb.toString();
    }

    private static String capitalize(String s) {
        return s.isEmpty() ? s : Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }
}
