#!/usr/bin/env bash
set -euo pipefail
./mvnw package -DskipTests -DskipShade=false
java \
  --add-opens java.base/java.nio=ALL-UNNAMED \
  --enable-native-access=ALL-UNNAMED \
  --sun-misc-unsafe-memory-access=allow \
  -jar performance/target/benchmarks.jar \
  "${@:-.+}" \
  -rf json \
  -rff performance/target/benchmark-result.json
