package io.github.dfa1.vortex.fuzz;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import com.code_intelligence.jazzer.junit.FuzzTest;
import io.github.dfa1.vortex.core.error.VortexException;
import io.github.dfa1.vortex.reader.VortexReader;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.io.TempDir;

/// Coverage-guided fuzzing of the full-file open path (ADR 0020). The reader's security contract
/// requires every malformed input to surface as a [VortexException] — anything else escaping this
/// driver (an [Error], a raw `IndexOutOfBoundsException`, a FlatBuffer/Protobuf parser exception)
/// is a real finding, so the fuzzer's pass/fail oracle is simply "no other throwable escapes".
///
/// There is no `VortexReader.open(byte[])`: the public API memory-maps a real file, so the fuzzer
/// bytes are written to a temp file and fed through the actual [VortexReader#open(Path)] entry
/// point — exactly the trailer / postscript / footer / layout / dtype parse path a malformed file
/// on disk would hit.
///
/// Tagged `fuzz` so a routine build skips it; run with
/// `./mvnw test -pl fuzz -am -Dvortex.fuzz.excludedGroups=`
/// (add `JAZZER_FUZZ=1` to actually explore new inputs rather than replay the corpus).
@Tag("fuzz")
class VortexReaderFuzzTest {

    // @FuzzTest defaults to PER_TEST lifecycle: the test instance — and therefore this injected
    // temp directory — is created once and reused across every fuzzing execution.
    @TempDir
    Path tempDir;

    private Path fuzzFile;

    @BeforeEach
    void setUp() {
        fuzzFile = tempDir.resolve("fuzz.vortex");
    }

    @FuzzTest
    void openMalformedFile(byte[] data) throws IOException {
        Files.write(fuzzFile, data);
        try (var _ = VortexReader.open(fuzzFile)) {
            // Successfully opened: fine. The security contract only requires that MALFORMED input
            // fails as VortexException, not that every fuzzer-generated byte string is rejected.
        } catch (VortexException expected) {
            // Malformed input correctly rejected per the reader's security contract.
        }
    }
}
