// automatically generated by the FlatBuffers compiler, do not modify

package io.github.dfa1.vortex.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Array extends com.google.flatbuffers.Table {
  public static Array getRootAsArray(ByteBuffer _bb) { return getRootAsArray(_bb, new Array()); }
  public static Array getRootAsArray(ByteBuffer _bb, Array obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Array __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * The array's hierarchical definition.
   */
  public io.github.dfa1.vortex.fbs.ArrayNode root() { return root(new io.github.dfa1.vortex.fbs.ArrayNode()); }
  public io.github.dfa1.vortex.fbs.ArrayNode root(io.github.dfa1.vortex.fbs.ArrayNode obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  /**
   * The locations of the data buffers of the array
   */
  public io.github.dfa1.vortex.fbs.Buffer buffers(int j) { return buffers(new io.github.dfa1.vortex.fbs.Buffer(), j); }
  public io.github.dfa1.vortex.fbs.Buffer buffers(io.github.dfa1.vortex.fbs.Buffer obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o) + j * 8, bb) : null; }
  public int buffersLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public io.github.dfa1.vortex.fbs.Buffer.Vector buffersVector() { return buffersVector(new io.github.dfa1.vortex.fbs.Buffer.Vector()); }
  public io.github.dfa1.vortex.fbs.Buffer.Vector buffersVector(io.github.dfa1.vortex.fbs.Buffer.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 8, bb) : null; }

  public static int createArray(FlatBufferBuilder builder,
      int rootOffset,
      int buffersOffset) {
    builder.startTable(2);
    Array.addBuffers(builder, buffersOffset);
    Array.addRoot(builder, rootOffset);
    return Array.endArray(builder);
  }

  public static void startArray(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addRoot(FlatBufferBuilder builder, int rootOffset) { builder.addOffset(0, rootOffset, 0); }
  public static void addBuffers(FlatBufferBuilder builder, int buffersOffset) { builder.addOffset(1, buffersOffset, 0); }
  public static void startBuffersVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 4); }
  public static int endArray(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishArrayBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedArrayBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Array get(int j) { return get(new Array(), j); }
    public Array get(Array obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

