// automatically generated by the FlatBuffers compiler, do not modify

package io.github.dfa1.vortex.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ArrayNode extends com.google.flatbuffers.Table {
  public static ArrayNode getRootAsArrayNode(ByteBuffer _bb) { return getRootAsArrayNode(_bb, new ArrayNode()); }
  public static ArrayNode getRootAsArrayNode(ByteBuffer _bb, ArrayNode obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ArrayNode __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int encoding() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public int metadata(int j) { int o = __offset(6); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int metadataLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector metadataVector() { return metadataVector(new ByteVector()); }
  public ByteVector metadataVector(ByteVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer metadataAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer metadataInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public io.github.dfa1.vortex.fbs.ArrayNode children(int j) { return children(new io.github.dfa1.vortex.fbs.ArrayNode(), j); }
  public io.github.dfa1.vortex.fbs.ArrayNode children(io.github.dfa1.vortex.fbs.ArrayNode obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int childrenLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public io.github.dfa1.vortex.fbs.ArrayNode.Vector childrenVector() { return childrenVector(new io.github.dfa1.vortex.fbs.ArrayNode.Vector()); }
  public io.github.dfa1.vortex.fbs.ArrayNode.Vector childrenVector(io.github.dfa1.vortex.fbs.ArrayNode.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public int buffers(int j) { int o = __offset(10); return o != 0 ? bb.getShort(__vector(o) + j * 2) & 0xFFFF : 0; }
  public int buffersLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public ShortVector buffersVector() { return buffersVector(new ShortVector()); }
  public ShortVector buffersVector(ShortVector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer buffersAsByteBuffer() { return __vector_as_bytebuffer(10, 2); }
  public ByteBuffer buffersInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 2); }
  public io.github.dfa1.vortex.fbs.ArrayStats stats() { return stats(new io.github.dfa1.vortex.fbs.ArrayStats()); }
  public io.github.dfa1.vortex.fbs.ArrayStats stats(io.github.dfa1.vortex.fbs.ArrayStats obj) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createArrayNode(FlatBufferBuilder builder,
      int encoding,
      int metadataOffset,
      int childrenOffset,
      int buffersOffset,
      int statsOffset) {
    builder.startTable(5);
    ArrayNode.addStats(builder, statsOffset);
    ArrayNode.addBuffers(builder, buffersOffset);
    ArrayNode.addChildren(builder, childrenOffset);
    ArrayNode.addMetadata(builder, metadataOffset);
    ArrayNode.addEncoding(builder, encoding);
    return ArrayNode.endArrayNode(builder);
  }

  public static void startArrayNode(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addEncoding(FlatBufferBuilder builder, int encoding) { builder.addShort(0, (short) encoding, (short) 0); }
  public static void addMetadata(FlatBufferBuilder builder, int metadataOffset) { builder.addOffset(1, metadataOffset, 0); }
  public static int createMetadataVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createMetadataVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startMetadataVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addChildren(FlatBufferBuilder builder, int childrenOffset) { builder.addOffset(2, childrenOffset, 0); }
  public static int createChildrenVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startChildrenVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addBuffers(FlatBufferBuilder builder, int buffersOffset) { builder.addOffset(3, buffersOffset, 0); }
  public static int createBuffersVector(FlatBufferBuilder builder, int[] data) { builder.startVector(2, data.length, 2); for (int i = data.length - 1; i >= 0; i--) builder.addShort((short) data[i]); return builder.endVector(); }
  public static void startBuffersVector(FlatBufferBuilder builder, int numElems) { builder.startVector(2, numElems, 2); }
  public static void addStats(FlatBufferBuilder builder, int statsOffset) { builder.addOffset(4, statsOffset, 0); }
  public static int endArrayNode(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ArrayNode get(int j) { return get(new ArrayNode(), j); }
    public ArrayNode get(ArrayNode obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

