// automatically generated by the FlatBuffers compiler, do not modify

package io.github.dfa1.vortex.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Binary extends com.google.flatbuffers.Table {
  public static Binary getRootAsBinary(ByteBuffer _bb) { return getRootAsBinary(_bb, new Binary()); }
  public static Binary getRootAsBinary(ByteBuffer _bb, Binary obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Binary __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean nullable() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createBinary(FlatBufferBuilder builder,
      boolean nullable) {
    builder.startTable(1);
    Binary.addNullable(builder, nullable);
    return Binary.endBinary(builder);
  }

  public static void startBinary(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addNullable(FlatBufferBuilder builder, boolean nullable) { builder.addBoolean(0, nullable, false); }
  public static int endBinary(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Binary get(int j) { return get(new Binary(), j); }
    public Binary get(Binary obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

