// automatically generated by the FlatBuffers compiler, do not modify

package io.github.dfa1.vortex.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.FlatBufferBuilder;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Bool extends com.google.flatbuffers.Table {
    public static Bool getRootAsBool(ByteBuffer _bb) {
        return getRootAsBool(_bb, new Bool());
    }

    public static Bool getRootAsBool(ByteBuffer _bb, Bool obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public static int createBool(FlatBufferBuilder builder,
            boolean nullable) {
        builder.startTable(1);
        Bool.addNullable(builder, nullable);
        return Bool.endBool(builder);
    }

    public static void startBool(FlatBufferBuilder builder) {
        builder.startTable(1);
    }

    public static void addNullable(FlatBufferBuilder builder, boolean nullable) {
        builder.addBoolean(0, nullable, false);
    }

    public static int endBool(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public Bool __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public boolean nullable() {
        int o = __offset(4);
        return o != 0 ? 0 != bb.get(o + bb_pos) : false;
    }

    public static final class Vector extends BaseVector {
        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public Bool get(int j) {
            return get(new Bool(), j);
        }

        public Bool get(Bool obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}

