// automatically generated by the FlatBuffers compiler, do not modify

package io.github.dfa1.vortex.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * A Buffer describes the location of a data buffer in the byte stream as a packed 64-bit struct.
 */
@SuppressWarnings("unused")
public final class Buffer extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Buffer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * The length of any padding bytes written immediately before the buffer.
   */
  public int padding() { return bb.getShort(bb_pos + 0) & 0xFFFF; }
  /**
   * The minimum alignment of the buffer, stored as an exponent of 2.
   */
  public int alignmentExponent() { return bb.get(bb_pos + 2) & 0xFF; }
  /**
   * The compression algorithm used to compress the buffer.
   */
  public int compression() { return bb.get(bb_pos + 3) & 0xFF; }
  /**
   * The length of the buffer in bytes.
   */
  public long length() { return (long)bb.getInt(bb_pos + 4) & 0xFFFFFFFFL; }

  public static int createBuffer(FlatBufferBuilder builder, int padding, int alignmentExponent, int compression, long length) {
    builder.prep(4, 8);
    builder.putInt((int) length);
    builder.putByte((byte) compression);
    builder.putByte((byte) alignmentExponent);
    builder.putShort((short) padding);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Buffer get(int j) { return get(new Buffer(), j); }
    public Buffer get(Buffer obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

