// automatically generated by the FlatBuffers compiler, do not modify

package io.github.dfa1.vortex.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.FlatBufferBuilder;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * Definition of a compression scheme.
 */
@SuppressWarnings("unused")
public final class CompressionSpec extends com.google.flatbuffers.Table {
    public static CompressionSpec getRootAsCompressionSpec(ByteBuffer _bb) {
        return getRootAsCompressionSpec(_bb, new CompressionSpec());
    }

    public static CompressionSpec getRootAsCompressionSpec(ByteBuffer _bb, CompressionSpec obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public static int createCompressionSpec(FlatBufferBuilder builder,
            int scheme) {
        builder.startTable(1);
        CompressionSpec.addScheme(builder, scheme);
        return CompressionSpec.endCompressionSpec(builder);
    }

    public static void startCompressionSpec(FlatBufferBuilder builder) {
        builder.startTable(1);
    }

    public static void addScheme(FlatBufferBuilder builder, int scheme) {
        builder.addByte(0, (byte) scheme, (byte) 0);
    }

    public static int endCompressionSpec(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public CompressionSpec __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public int scheme() {
        int o = __offset(4);
        return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0;
    }

    public static final class Vector extends BaseVector {
        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public CompressionSpec get(int j) {
            return get(new CompressionSpec(), j);
        }

        public CompressionSpec get(CompressionSpec obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}

