// automatically generated by the FlatBuffers compiler, do not modify

package io.github.dfa1.vortex.fbs;

@SuppressWarnings("unused")
public final class CompressionScheme {
    public static final int None = 0;
    public static final int LZ4 = 1;
    public static final int ZLib = 2;
    public static final int ZStd = 3;
    public static final String[] names = {"None", "LZ4", "ZLib", "ZStd",};

    private CompressionScheme() {
    }

    public static String name(int e) {
        return names[e];
    }
}

