// automatically generated by the FlatBuffers compiler, do not modify

package io.github.dfa1.vortex.fbs;

/**
 * The compression mechanism used to compress the buffer.
 */
@SuppressWarnings("unused")
public final class Compression {
  private Compression() { }
  public static final int None = 0;
  public static final int LZ4 = 1;

  public static final String[] names = { "None", "LZ4", };

  public static String name(int e) { return names[e]; }
}

