// automatically generated by the FlatBuffers compiler, do not modify

package io.github.dfa1.vortex.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.FlatBufferBuilder;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Extension extends com.google.flatbuffers.Table {
    public static Extension getRootAsExtension(ByteBuffer _bb) {
        return getRootAsExtension(_bb, new Extension());
    }

    public static Extension getRootAsExtension(ByteBuffer _bb, Extension obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public static int createExtension(FlatBufferBuilder builder,
            int idOffset,
            int storageDtypeOffset,
            int metadataOffset) {
        builder.startTable(3);
        Extension.addMetadata(builder, metadataOffset);
        Extension.addStorageDtype(builder, storageDtypeOffset);
        Extension.addId(builder, idOffset);
        return Extension.endExtension(builder);
    }

    public static void startExtension(FlatBufferBuilder builder) {
        builder.startTable(3);
    }

    public static void addId(FlatBufferBuilder builder, int idOffset) {
        builder.addOffset(0, idOffset, 0);
    }

    public static void addStorageDtype(FlatBufferBuilder builder, int storageDtypeOffset) {
        builder.addOffset(1, storageDtypeOffset, 0);
    }

    public static void addMetadata(FlatBufferBuilder builder, int metadataOffset) {
        builder.addOffset(2, metadataOffset, 0);
    }

    public static int createMetadataVector(FlatBufferBuilder builder, byte[] data) {
        return builder.createByteVector(data);
    }

    public static int createMetadataVector(FlatBufferBuilder builder, ByteBuffer data) {
        return builder.createByteVector(data);
    }

    public static void startMetadataVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(1, numElems, 1);
    }

    public static int endExtension(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public Extension __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public String id() {
        int o = __offset(4);
        return o != 0 ? __string(o + bb_pos) : null;
    }

    public ByteBuffer idAsByteBuffer() {
        return __vector_as_bytebuffer(4, 1);
    }

    public ByteBuffer idInByteBuffer(ByteBuffer _bb) {
        return __vector_in_bytebuffer(_bb, 4, 1);
    }

    public io.github.dfa1.vortex.fbs.DType storageDtype() {
        return storageDtype(new io.github.dfa1.vortex.fbs.DType());
    }

    public io.github.dfa1.vortex.fbs.DType storageDtype(io.github.dfa1.vortex.fbs.DType obj) {
        int o = __offset(6);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public int metadata(int j) {
        int o = __offset(8);
        return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0;
    }

    public int metadataLength() {
        int o = __offset(8);
        return o != 0 ? __vector_len(o) : 0;
    }

    public ByteVector metadataVector() {
        return metadataVector(new ByteVector());
    }

    public ByteVector metadataVector(ByteVector obj) {
        int o = __offset(8);
        return o != 0 ? obj.__assign(__vector(o), bb) : null;
    }

    public ByteBuffer metadataAsByteBuffer() {
        return __vector_as_bytebuffer(8, 1);
    }

    public ByteBuffer metadataInByteBuffer(ByteBuffer _bb) {
        return __vector_in_bytebuffer(_bb, 8, 1);
    }

    public static final class Vector extends BaseVector {
        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public Extension get(int j) {
            return get(new Extension(), j);
        }

        public Extension get(Extension obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}

