// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.fbs;

import io.github.dfa1.vortex.fbsrt.FbsBuilder;
import io.github.dfa1.vortex.fbsrt.FbsStruct;
import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `Buffer` FlatBuffers struct (inline, 8 bytes).
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsBuffer extends FbsStruct {

    /// Positions this reader at a struct.
    /// @param seg the buffer
    /// @param position the struct position
    /// @return this
    public FbsBuffer assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the `padding` field
    public int padding() {
        return readShort(0) & 0xFFFF;
    }

    /// @return the `alignmentExponent` field
    public int alignmentExponent() {
        return readByte(2) & 0xFF;
    }

    /// @return the `compression` field
    public int compression() {
        return readByte(3) & 0xFF;
    }

    /// @return the `length` field
    public long length() {
        return readInt(4) & 0xFFFFFFFFL;
    }

    /// Writes an inline `FbsBuffer` struct.
    /// @param b the builder
    /// @param padding field value
    /// @param alignmentExponent field value
    /// @param compression field value
    /// @param length field value
    /// @return the struct offset
    public static int createFbsBuffer(FbsBuilder b, int padding, int alignmentExponent, int compression, long length) {
        b.prep(4, 8);
        b.putInt((int) length);
        b.putByte((byte) compression);
        b.putByte((byte) alignmentExponent);
        b.putShort((short) padding);
        return b.offset();
    }
}
