// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.fbs;

import javax.annotation.processing.Generated;

/// Constants for the `Compression` FlatBuffers enum.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsCompression {

    private FbsCompression() {
    }

    /// `None` = 0
    public static final byte None = (byte) 0;

    /// `LZ4` = 1
    public static final byte LZ4 = (byte) 1;
}
