// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.fbs;

import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `DType` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsDType extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsDType getRootAsFbsDType(MemorySegment seg) {
        return new FbsDType().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsDType assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the union discriminator for `type` (0 = none)
    public int typeType() {
        int o = fieldOffset(4);
        return o != 0 ? readByte(pos + o) & 0xFF : 0;
    }

    /// Projects the selected `type` member onto the given reader.
    /// @param obj a reader for the expected member type
    /// @param <T> the member reader type
    /// @return the positioned reader, or null if the union is absent
    public <T extends FbsTable> T type(T obj) {
        int o = fieldOffset(6);
        return o != 0 ? locate(obj, unionMemberPosition(o)) : null;
    }

    /// Sets the `typeType` field.
    /// @param b the builder
    /// @param value the value
    public static void addTypeType(FbsBuilder b, byte value) {
        b.addByte(0, value, 0);
    }

    /// Sets the `type` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addType(FbsBuilder b, int offset) {
        b.addOffset(1, offset, 0);
    }

    /// Builds a `FbsDType` table.
    /// @param b the builder
    /// @param typeType field value
    /// @param typeOffset field value
    /// @return the table offset
    public static int createFbsDType(FbsBuilder b, byte typeType, int typeOffset) {
        b.startTable(2);
        b.addOffset(1, typeOffset, 0);
        b.addByte(0, typeType, 0);
        return b.endTable();
    }

    /// Begins a `FbsDType` table.
    /// @param b the builder
    public static void startFbsDType(FbsBuilder b) {
        b.startTable(2);
    }

    /// Finishes a `FbsDType` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsDType(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsDType` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsDTypeBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
