// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.fbs;

import io.github.dfa1.vortex.fbsrt.FbsBuilder;
import io.github.dfa1.vortex.fbsrt.FbsTable;
import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `Decimal` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsDecimal extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsDecimal getRootAsFbsDecimal(MemorySegment seg) {
        return new FbsDecimal().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsDecimal assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the `precision` field
    public int precision() {
        int o = fieldOffset(4);
        return o != 0 ? readByte(pos + o) & 0xFF : 0;
    }

    /// @return the `scale` field
    public int scale() {
        int o = fieldOffset(6);
        return o != 0 ? (int) readByte(pos + o) : 0;
    }

    /// @return the `nullable` field
    public boolean nullable() {
        int o = fieldOffset(8);
        return o != 0 ? readByte(pos + o) != 0 : false;
    }

    /// Sets the `precision` field.
    /// @param b the builder
    /// @param precision value
    public static void addPrecision(FbsBuilder b, int precision) {
        b.addByte(0, (byte) precision, 0);
    }

    /// Sets the `scale` field.
    /// @param b the builder
    /// @param scale value
    public static void addScale(FbsBuilder b, int scale) {
        b.addByte(1, (byte) scale, 0);
    }

    /// Sets the `nullable` field.
    /// @param b the builder
    /// @param nullable value
    public static void addNullable(FbsBuilder b, boolean nullable) {
        b.addBoolean(2, nullable, false);
    }

    /// Builds a `FbsDecimal` table.
    /// @param b the builder
    /// @param precision field value
    /// @param scale field value
    /// @param nullable field value
    /// @return the table offset
    public static int createFbsDecimal(FbsBuilder b, int precision, int scale, boolean nullable) {
        b.startTable(3);
        b.addBoolean(2, nullable, false);
        b.addByte(1, (byte) scale, 0);
        b.addByte(0, (byte) precision, 0);
        return b.endTable();
    }

    /// Begins a `FbsDecimal` table.
    /// @param b the builder
    public static void startFbsDecimal(FbsBuilder b) {
        b.startTable(3);
    }

    /// Finishes a `FbsDecimal` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsDecimal(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsDecimal` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsDecimalBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
