// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.fbs;

import io.github.dfa1.vortex.fbsrt.FbsBuilder;
import io.github.dfa1.vortex.fbsrt.FbsTable;
import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `FileStatistics` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsFileStatistics extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsFileStatistics getRootAsFbsFileStatistics(MemorySegment seg) {
        return new FbsFileStatistics().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsFileStatistics assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the length of the `fieldStats` vector
    public int fieldStatsLength() {
        int o = fieldOffset(4);
        return o != 0 ? vectorLength(o) : 0;
    }

    /// @param j element index
    /// @return the j-th `fieldStats` element
    public FbsArrayStats fieldStats(int j) {
        int o = fieldOffset(4);
        return new FbsArrayStats().assign(seg, indirect(vectorElements(o) + (long) j * 4));
    }

    /// Sets the `fieldStats` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addFieldStats(FbsBuilder b, int offset) {
        b.addOffset(0, offset, 0);
    }

    /// Creates the `fieldStats` offset vector.
    /// @param b the builder
    /// @param data element offsets
    /// @return the vector offset
    public static int createFieldStatsVector(FbsBuilder b, int[] data) {
        b.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) {
            b.addOffset(data[i]);
        }
        return b.endVector();
    }

    /// Begins the `fieldStats` vector.
    /// @param b the builder
    /// @param numElems element count
    public static void startFieldStatsVector(FbsBuilder b, int numElems) {
        b.startVector(4, numElems, 4);
    }

    /// Builds a `FbsFileStatistics` table.
    /// @param b the builder
    /// @param fieldStatsOffset field value
    /// @return the table offset
    public static int createFbsFileStatistics(FbsBuilder b, int fieldStatsOffset) {
        b.startTable(1);
        b.addOffset(0, fieldStatsOffset, 0);
        return b.endTable();
    }

    /// Begins a `FbsFileStatistics` table.
    /// @param b the builder
    public static void startFbsFileStatistics(FbsBuilder b) {
        b.startTable(1);
    }

    /// Finishes a `FbsFileStatistics` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsFileStatistics(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsFileStatistics` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsFileStatisticsBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
