// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.fbs;

import io.github.dfa1.vortex.fbsrt.FbsBuilder;
import io.github.dfa1.vortex.fbsrt.FbsTable;
import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `FixedSizeList` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsFixedSizeList extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsFixedSizeList getRootAsFbsFixedSizeList(MemorySegment seg) {
        return new FbsFixedSizeList().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsFixedSizeList assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the `elementType` child, or null if absent
    public FbsDType elementType() {
        int o = fieldOffset(4);
        return o != 0 ? new FbsDType().assign(seg, indirect(pos + o)) : null;
    }

    /// @return the `size` field
    public long size() {
        int o = fieldOffset(6);
        return o != 0 ? readInt(pos + o) & 0xFFFFFFFFL : 0L;
    }

    /// @return the `nullable` field
    public boolean nullable() {
        int o = fieldOffset(8);
        return o != 0 ? readByte(pos + o) != 0 : false;
    }

    /// Sets the `elementType` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addElementType(FbsBuilder b, int offset) {
        b.addOffset(0, offset, 0);
    }

    /// Sets the `size` field.
    /// @param b the builder
    /// @param size value
    public static void addSize(FbsBuilder b, long size) {
        b.addInt(1, (int) size, 0);
    }

    /// Sets the `nullable` field.
    /// @param b the builder
    /// @param nullable value
    public static void addNullable(FbsBuilder b, boolean nullable) {
        b.addBoolean(2, nullable, false);
    }

    /// Builds a `FbsFixedSizeList` table.
    /// @param b the builder
    /// @param elementTypeOffset field value
    /// @param size field value
    /// @param nullable field value
    /// @return the table offset
    public static int createFbsFixedSizeList(FbsBuilder b, int elementTypeOffset, long size, boolean nullable) {
        b.startTable(3);
        b.addInt(1, (int) size, 0);
        b.addOffset(0, elementTypeOffset, 0);
        b.addBoolean(2, nullable, false);
        return b.endTable();
    }

    /// Begins a `FbsFixedSizeList` table.
    /// @param b the builder
    public static void startFbsFixedSizeList(FbsBuilder b) {
        b.startTable(3);
    }

    /// Finishes a `FbsFixedSizeList` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsFixedSizeList(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsFixedSizeList` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsFixedSizeListBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
