// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.fbs;

import io.github.dfa1.vortex.fbsrt.FbsBuilder;
import io.github.dfa1.vortex.fbsrt.FbsTable;
import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `Footer` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsFooter extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsFooter getRootAsFbsFooter(MemorySegment seg) {
        return new FbsFooter().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsFooter assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the length of the `arraySpecs` vector
    public int arraySpecsLength() {
        int o = fieldOffset(4);
        return o != 0 ? vectorLength(o) : 0;
    }

    /// @param j element index
    /// @return the j-th `arraySpecs` element
    public FbsArraySpec arraySpecs(int j) {
        int o = fieldOffset(4);
        return new FbsArraySpec().assign(seg, indirect(vectorElements(o) + (long) j * 4));
    }

    /// @return the length of the `layoutSpecs` vector
    public int layoutSpecsLength() {
        int o = fieldOffset(6);
        return o != 0 ? vectorLength(o) : 0;
    }

    /// @param j element index
    /// @return the j-th `layoutSpecs` element
    public FbsLayoutSpec layoutSpecs(int j) {
        int o = fieldOffset(6);
        return new FbsLayoutSpec().assign(seg, indirect(vectorElements(o) + (long) j * 4));
    }

    /// @return the length of the `segmentSpecs` vector
    public int segmentSpecsLength() {
        int o = fieldOffset(8);
        return o != 0 ? vectorLength(o) : 0;
    }

    /// @param j element index
    /// @return the j-th `segmentSpecs` element
    public FbsSegmentSpec segmentSpecs(int j) {
        int o = fieldOffset(8);
        return new FbsSegmentSpec().assign(seg, vectorElements(o) + (long) j * 16);
    }

    /// @return the length of the `compressionSpecs` vector
    public int compressionSpecsLength() {
        int o = fieldOffset(10);
        return o != 0 ? vectorLength(o) : 0;
    }

    /// @param j element index
    /// @return the j-th `compressionSpecs` element
    public FbsCompressionSpec compressionSpecs(int j) {
        int o = fieldOffset(10);
        return new FbsCompressionSpec().assign(seg, indirect(vectorElements(o) + (long) j * 4));
    }

    /// @return the length of the `encryptionSpecs` vector
    public int encryptionSpecsLength() {
        int o = fieldOffset(12);
        return o != 0 ? vectorLength(o) : 0;
    }

    /// @param j element index
    /// @return the j-th `encryptionSpecs` element
    public FbsEncryptionSpec encryptionSpecs(int j) {
        int o = fieldOffset(12);
        return new FbsEncryptionSpec().assign(seg, indirect(vectorElements(o) + (long) j * 4));
    }

    /// Sets the `arraySpecs` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addArraySpecs(FbsBuilder b, int offset) {
        b.addOffset(0, offset, 0);
    }

    /// Creates the `arraySpecs` offset vector.
    /// @param b the builder
    /// @param data element offsets
    /// @return the vector offset
    public static int createArraySpecsVector(FbsBuilder b, int[] data) {
        b.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) {
            b.addOffset(data[i]);
        }
        return b.endVector();
    }

    /// Begins the `arraySpecs` vector.
    /// @param b the builder
    /// @param numElems element count
    public static void startArraySpecsVector(FbsBuilder b, int numElems) {
        b.startVector(4, numElems, 4);
    }

    /// Sets the `layoutSpecs` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addLayoutSpecs(FbsBuilder b, int offset) {
        b.addOffset(1, offset, 0);
    }

    /// Creates the `layoutSpecs` offset vector.
    /// @param b the builder
    /// @param data element offsets
    /// @return the vector offset
    public static int createLayoutSpecsVector(FbsBuilder b, int[] data) {
        b.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) {
            b.addOffset(data[i]);
        }
        return b.endVector();
    }

    /// Begins the `layoutSpecs` vector.
    /// @param b the builder
    /// @param numElems element count
    public static void startLayoutSpecsVector(FbsBuilder b, int numElems) {
        b.startVector(4, numElems, 4);
    }

    /// Sets the `segmentSpecs` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addSegmentSpecs(FbsBuilder b, int offset) {
        b.addOffset(2, offset, 0);
    }

    /// Begins the `segmentSpecs` vector.
    /// @param b the builder
    /// @param numElems element count
    public static void startSegmentSpecsVector(FbsBuilder b, int numElems) {
        b.startVector(16, numElems, 8);
    }

    /// Sets the `compressionSpecs` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addCompressionSpecs(FbsBuilder b, int offset) {
        b.addOffset(3, offset, 0);
    }

    /// Creates the `compressionSpecs` offset vector.
    /// @param b the builder
    /// @param data element offsets
    /// @return the vector offset
    public static int createCompressionSpecsVector(FbsBuilder b, int[] data) {
        b.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) {
            b.addOffset(data[i]);
        }
        return b.endVector();
    }

    /// Begins the `compressionSpecs` vector.
    /// @param b the builder
    /// @param numElems element count
    public static void startCompressionSpecsVector(FbsBuilder b, int numElems) {
        b.startVector(4, numElems, 4);
    }

    /// Sets the `encryptionSpecs` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addEncryptionSpecs(FbsBuilder b, int offset) {
        b.addOffset(4, offset, 0);
    }

    /// Creates the `encryptionSpecs` offset vector.
    /// @param b the builder
    /// @param data element offsets
    /// @return the vector offset
    public static int createEncryptionSpecsVector(FbsBuilder b, int[] data) {
        b.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) {
            b.addOffset(data[i]);
        }
        return b.endVector();
    }

    /// Begins the `encryptionSpecs` vector.
    /// @param b the builder
    /// @param numElems element count
    public static void startEncryptionSpecsVector(FbsBuilder b, int numElems) {
        b.startVector(4, numElems, 4);
    }

    /// Builds a `FbsFooter` table.
    /// @param b the builder
    /// @param arraySpecsOffset field value
    /// @param layoutSpecsOffset field value
    /// @param segmentSpecsOffset field value
    /// @param compressionSpecsOffset field value
    /// @param encryptionSpecsOffset field value
    /// @return the table offset
    public static int createFbsFooter(FbsBuilder b, int arraySpecsOffset, int layoutSpecsOffset, int segmentSpecsOffset, int compressionSpecsOffset, int encryptionSpecsOffset) {
        b.startTable(5);
        b.addOffset(4, encryptionSpecsOffset, 0);
        b.addOffset(3, compressionSpecsOffset, 0);
        b.addOffset(2, segmentSpecsOffset, 0);
        b.addOffset(1, layoutSpecsOffset, 0);
        b.addOffset(0, arraySpecsOffset, 0);
        return b.endTable();
    }

    /// Begins a `FbsFooter` table.
    /// @param b the builder
    public static void startFbsFooter(FbsBuilder b) {
        b.startTable(5);
    }

    /// Finishes a `FbsFooter` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsFooter(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsFooter` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsFooterBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
