// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.fbs;

import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `Layout` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsLayout extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsLayout getRootAsFbsLayout(MemorySegment seg) {
        return new FbsLayout().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsLayout assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the `encoding` field
    public int encoding() {
        int o = fieldOffset(4);
        return o != 0 ? readShort(pos + o) & 0xFFFF : 0;
    }

    /// @return the `rowCount` field
    public long rowCount() {
        int o = fieldOffset(6);
        return o != 0 ? readLong(pos + o) : 0L;
    }

    /// @return the length of the `metadata` vector
    public int metadataLength() {
        int o = fieldOffset(8);
        return o != 0 ? vectorLength(o) : 0;
    }

    /// @param j element index
    /// @return the j-th `metadata` element
    public int metadata(int j) {
        int o = fieldOffset(8);
        return o != 0 ? readByte(vectorElements(o) + (long) j * 1) & 0xFF : 0;
    }

    /// @return a zero-copy slice of the `metadata` byte vector, or null if absent
    public MemorySegment metadataAsSegment() {
        int o = fieldOffset(8);
        return o != 0 ? byteVector(o) : null;
    }

    /// @return the length of the `children` vector
    public int childrenLength() {
        int o = fieldOffset(10);
        return o != 0 ? vectorLength(o) : 0;
    }

    /// @param j element index
    /// @return the j-th `children` element
    public FbsLayout children(int j) {
        int o = fieldOffset(10);
        return new FbsLayout().assign(seg, indirect(vectorElements(o) + (long) j * 4));
    }

    /// @return the length of the `segments` vector
    public int segmentsLength() {
        int o = fieldOffset(12);
        return o != 0 ? vectorLength(o) : 0;
    }

    /// @param j element index
    /// @return the j-th `segments` element
    public long segments(int j) {
        int o = fieldOffset(12);
        return o != 0 ? readInt(vectorElements(o) + (long) j * 4) & 0xFFFFFFFFL : 0L;
    }

    /// Sets the `encoding` field.
    /// @param b the builder
    /// @param encoding value
    public static void addEncoding(FbsBuilder b, int encoding) {
        b.addShort(0, (short) encoding, 0);
    }

    /// Sets the `rowCount` field.
    /// @param b the builder
    /// @param rowCount value
    public static void addRowCount(FbsBuilder b, long rowCount) {
        b.addLong(1, rowCount, 0L);
    }

    /// Sets the `metadata` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addMetadata(FbsBuilder b, int offset) {
        b.addOffset(2, offset, 0);
    }

    /// Creates the `metadata` byte vector.
    /// @param b the builder
    /// @param data the bytes
    /// @return the vector offset
    public static int createMetadataVector(FbsBuilder b, byte[] data) {
        return b.createByteVector(data);
    }

    /// Begins the `metadata` vector.
    /// @param b the builder
    /// @param numElems element count
    public static void startMetadataVector(FbsBuilder b, int numElems) {
        b.startVector(1, numElems, 1);
    }

    /// Sets the `children` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addChildren(FbsBuilder b, int offset) {
        b.addOffset(3, offset, 0);
    }

    /// Creates the `children` offset vector.
    /// @param b the builder
    /// @param data element offsets
    /// @return the vector offset
    public static int createChildrenVector(FbsBuilder b, int[] data) {
        b.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) {
            b.addOffset(data[i]);
        }
        return b.endVector();
    }

    /// Begins the `children` vector.
    /// @param b the builder
    /// @param numElems element count
    public static void startChildrenVector(FbsBuilder b, int numElems) {
        b.startVector(4, numElems, 4);
    }

    /// Sets the `segments` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addSegments(FbsBuilder b, int offset) {
        b.addOffset(4, offset, 0);
    }

    /// Creates the `segments` vector.
    /// @param b the builder
    /// @param data the elements
    /// @return the vector offset
    public static int createSegmentsVector(FbsBuilder b, long[] data) {
        b.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) {
            b.addInt((int) data[i]);
        }
        return b.endVector();
    }

    /// Begins the `segments` vector.
    /// @param b the builder
    /// @param numElems element count
    public static void startSegmentsVector(FbsBuilder b, int numElems) {
        b.startVector(4, numElems, 4);
    }

    /// Builds a `FbsLayout` table.
    /// @param b the builder
    /// @param encoding field value
    /// @param rowCount field value
    /// @param metadataOffset field value
    /// @param childrenOffset field value
    /// @param segmentsOffset field value
    /// @return the table offset
    public static int createFbsLayout(FbsBuilder b, int encoding, long rowCount, int metadataOffset, int childrenOffset, int segmentsOffset) {
        b.startTable(5);
        b.addLong(1, rowCount, 0L);
        b.addOffset(4, segmentsOffset, 0);
        b.addOffset(3, childrenOffset, 0);
        b.addOffset(2, metadataOffset, 0);
        b.addShort(0, (short) encoding, 0);
        return b.endTable();
    }

    /// Begins a `FbsLayout` table.
    /// @param b the builder
    public static void startFbsLayout(FbsBuilder b) {
        b.startTable(5);
    }

    /// Finishes a `FbsLayout` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsLayout(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsLayout` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsLayoutBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
