// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.fbs;

import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `Null` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsNull extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsNull getRootAsFbsNull(MemorySegment seg) {
        return new FbsNull().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsNull assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// Builds a `FbsNull` table.
    /// @param b the builder
    /// @return the table offset
    public static int createFbsNull(FbsBuilder b) {
        b.startTable(0);
        return b.endTable();
    }

    /// Begins a `FbsNull` table.
    /// @param b the builder
    public static void startFbsNull(FbsBuilder b) {
        b.startTable(0);
    }

    /// Finishes a `FbsNull` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsNull(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsNull` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsNullBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
