// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.fbs;

import javax.annotation.processing.Generated;

/// Constants for the `Precision` FlatBuffers enum.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsPrecision {

    private FbsPrecision() {
    }

    /// `Inexact` = 0
    public static final byte Inexact = (byte) 0;

    /// `Exact` = 1
    public static final byte Exact = (byte) 1;
}
