// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.fbs;

import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `PostscriptSegment` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsPostscriptSegment extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsPostscriptSegment getRootAsFbsPostscriptSegment(MemorySegment seg) {
        return new FbsPostscriptSegment().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsPostscriptSegment assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the `offset` field
    public long offset() {
        int o = fieldOffset(4);
        return o != 0 ? readLong(pos + o) : 0L;
    }

    /// @return the `length` field
    public long length() {
        int o = fieldOffset(6);
        return o != 0 ? readInt(pos + o) & 0xFFFFFFFFL : 0L;
    }

    /// @return the `alignmentExponent` field
    public int alignmentExponent() {
        int o = fieldOffset(8);
        return o != 0 ? readByte(pos + o) & 0xFF : 0;
    }

    /// @return the `compression` child, or null if absent
    public FbsCompressionSpec compression() {
        int o = fieldOffset(10);
        return o != 0 ? new FbsCompressionSpec().assign(seg, indirect(pos + o)) : null;
    }

    /// @return the `encryption` child, or null if absent
    public FbsEncryptionSpec encryption() {
        int o = fieldOffset(12);
        return o != 0 ? new FbsEncryptionSpec().assign(seg, indirect(pos + o)) : null;
    }

    /// Sets the `offset` field.
    /// @param b the builder
    /// @param offset value
    public static void addOffset(FbsBuilder b, long offset) {
        b.addLong(0, offset, 0L);
    }

    /// Sets the `length` field.
    /// @param b the builder
    /// @param length value
    public static void addLength(FbsBuilder b, long length) {
        b.addInt(1, (int) length, 0);
    }

    /// Sets the `alignmentExponent` field.
    /// @param b the builder
    /// @param alignmentExponent value
    public static void addAlignmentExponent(FbsBuilder b, int alignmentExponent) {
        b.addByte(2, (byte) alignmentExponent, 0);
    }

    /// Sets the `compression` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addCompression(FbsBuilder b, int offset) {
        b.addOffset(3, offset, 0);
    }

    /// Sets the `encryption` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addEncryption(FbsBuilder b, int offset) {
        b.addOffset(4, offset, 0);
    }

    /// Builds a `FbsPostscriptSegment` table.
    /// @param b the builder
    /// @param offset field value
    /// @param length field value
    /// @param alignmentExponent field value
    /// @param compressionOffset field value
    /// @param encryptionOffset field value
    /// @return the table offset
    public static int createFbsPostscriptSegment(FbsBuilder b, long offset, long length, int alignmentExponent, int compressionOffset, int encryptionOffset) {
        b.startTable(5);
        b.addLong(0, offset, 0L);
        b.addOffset(4, encryptionOffset, 0);
        b.addOffset(3, compressionOffset, 0);
        b.addInt(1, (int) length, 0);
        b.addByte(2, (byte) alignmentExponent, 0);
        return b.endTable();
    }

    /// Begins a `FbsPostscriptSegment` table.
    /// @param b the builder
    public static void startFbsPostscriptSegment(FbsBuilder b) {
        b.startTable(5);
    }

    /// Finishes a `FbsPostscriptSegment` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsPostscriptSegment(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsPostscriptSegment` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsPostscriptSegmentBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
