// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.fbs;

import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `Postscript` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsPostscript extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsPostscript getRootAsFbsPostscript(MemorySegment seg) {
        return new FbsPostscript().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsPostscript assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the `dtype` child, or null if absent
    public FbsPostscriptSegment dtype() {
        int o = fieldOffset(4);
        return o != 0 ? new FbsPostscriptSegment().assign(seg, indirect(pos + o)) : null;
    }

    /// @return the `layout` child, or null if absent
    public FbsPostscriptSegment layout() {
        int o = fieldOffset(6);
        return o != 0 ? new FbsPostscriptSegment().assign(seg, indirect(pos + o)) : null;
    }

    /// @return the `statistics` child, or null if absent
    public FbsPostscriptSegment statistics() {
        int o = fieldOffset(8);
        return o != 0 ? new FbsPostscriptSegment().assign(seg, indirect(pos + o)) : null;
    }

    /// @return the `footer` child, or null if absent
    public FbsPostscriptSegment footer() {
        int o = fieldOffset(10);
        return o != 0 ? new FbsPostscriptSegment().assign(seg, indirect(pos + o)) : null;
    }

    /// Sets the `dtype` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addDtype(FbsBuilder b, int offset) {
        b.addOffset(0, offset, 0);
    }

    /// Sets the `layout` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addLayout(FbsBuilder b, int offset) {
        b.addOffset(1, offset, 0);
    }

    /// Sets the `statistics` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addStatistics(FbsBuilder b, int offset) {
        b.addOffset(2, offset, 0);
    }

    /// Sets the `footer` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addFooter(FbsBuilder b, int offset) {
        b.addOffset(3, offset, 0);
    }

    /// Builds a `FbsPostscript` table.
    /// @param b the builder
    /// @param dtypeOffset field value
    /// @param layoutOffset field value
    /// @param statisticsOffset field value
    /// @param footerOffset field value
    /// @return the table offset
    public static int createFbsPostscript(FbsBuilder b, int dtypeOffset, int layoutOffset, int statisticsOffset, int footerOffset) {
        b.startTable(4);
        b.addOffset(3, footerOffset, 0);
        b.addOffset(2, statisticsOffset, 0);
        b.addOffset(1, layoutOffset, 0);
        b.addOffset(0, dtypeOffset, 0);
        return b.endTable();
    }

    /// Begins a `FbsPostscript` table.
    /// @param b the builder
    public static void startFbsPostscript(FbsBuilder b) {
        b.startTable(4);
    }

    /// Finishes a `FbsPostscript` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsPostscript(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsPostscript` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsPostscriptBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
