// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.fbs;

import javax.annotation.processing.Generated;

/// Constants for the `PType` FlatBuffers enum.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsPType {

    private FbsPType() {
    }

    /// `U8` = 0
    public static final byte U8 = (byte) 0;

    /// `U16` = 1
    public static final byte U16 = (byte) 1;

    /// `U32` = 2
    public static final byte U32 = (byte) 2;

    /// `U64` = 3
    public static final byte U64 = (byte) 3;

    /// `I8` = 4
    public static final byte I8 = (byte) 4;

    /// `I16` = 5
    public static final byte I16 = (byte) 5;

    /// `I32` = 6
    public static final byte I32 = (byte) 6;

    /// `I64` = 7
    public static final byte I64 = (byte) 7;

    /// `F16` = 8
    public static final byte F16 = (byte) 8;

    /// `F32` = 9
    public static final byte F32 = (byte) 9;

    /// `F64` = 10
    public static final byte F64 = (byte) 10;
}
