// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.fbs;

import io.github.dfa1.vortex.fbsrt.FbsBuilder;
import io.github.dfa1.vortex.fbsrt.FbsTable;
import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `Union` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsUnion extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsUnion getRootAsFbsUnion(MemorySegment seg) {
        return new FbsUnion().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsUnion assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the `nullable` field
    public boolean nullable() {
        int o = fieldOffset(4);
        return o != 0 ? readByte(pos + o) != 0 : false;
    }

    /// Sets the `nullable` field.
    /// @param b the builder
    /// @param nullable value
    public static void addNullable(FbsBuilder b, boolean nullable) {
        b.addBoolean(0, nullable, false);
    }

    /// Builds a `FbsUnion` table.
    /// @param b the builder
    /// @param nullable field value
    /// @return the table offset
    public static int createFbsUnion(FbsBuilder b, boolean nullable) {
        b.startTable(1);
        b.addBoolean(0, nullable, false);
        return b.endTable();
    }

    /// Begins a `FbsUnion` table.
    /// @param b the builder
    public static void startFbsUnion(FbsBuilder b) {
        b.startTable(1);
    }

    /// Finishes a `FbsUnion` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsUnion(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsUnion` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsUnionBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
