// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.fbs;

import io.github.dfa1.vortex.fbsrt.FbsBuilder;
import io.github.dfa1.vortex.fbsrt.FbsTable;
import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `Variant` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsVariant extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsVariant getRootAsFbsVariant(MemorySegment seg) {
        return new FbsVariant().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsVariant assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the `nullable` field
    public boolean nullable() {
        int o = fieldOffset(4);
        return o != 0 ? readByte(pos + o) != 0 : false;
    }

    /// Sets the `nullable` field.
    /// @param b the builder
    /// @param nullable value
    public static void addNullable(FbsBuilder b, boolean nullable) {
        b.addBoolean(0, nullable, false);
    }

    /// Builds a `FbsVariant` table.
    /// @param b the builder
    /// @param nullable field value
    /// @return the table offset
    public static int createFbsVariant(FbsBuilder b, boolean nullable) {
        b.startTable(1);
        b.addBoolean(0, nullable, false);
        return b.endTable();
    }

    /// Begins a `FbsVariant` table.
    /// @param b the builder
    public static void startFbsVariant(FbsBuilder b) {
        b.startTable(1);
    }

    /// Finishes a `FbsVariant` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsVariant(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsVariant` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsVariantBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
