// automatically generated by the FlatBuffers compiler, do not modify

package io.github.dfa1.vortex.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.FlatBufferBuilder;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * The `FileStatistics` object contains file-level statistics for the Vortex file.
 */
@SuppressWarnings("unused")
public final class FileStatistics extends com.google.flatbuffers.Table {
    public static FileStatistics getRootAsFileStatistics(ByteBuffer _bb) {
        return getRootAsFileStatistics(_bb, new FileStatistics());
    }

    public static FileStatistics getRootAsFileStatistics(ByteBuffer _bb, FileStatistics obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public static int createFileStatistics(FlatBufferBuilder builder,
            int fieldStatsOffset) {
        builder.startTable(1);
        FileStatistics.addFieldStats(builder, fieldStatsOffset);
        return FileStatistics.endFileStatistics(builder);
    }

    public static void startFileStatistics(FlatBufferBuilder builder) {
        builder.startTable(1);
    }

    public static void addFieldStats(FlatBufferBuilder builder, int fieldStatsOffset) {
        builder.addOffset(0, fieldStatsOffset, 0);
    }

    public static int createFieldStatsVector(FlatBufferBuilder builder, int[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]);
        return builder.endVector();
    }

    public static void startFieldStatsVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static int endFileStatistics(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public FileStatistics __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    /**
     * Statistics for each field in the root schema. If the root schema is not a struct, there will
     * be a single entry in this array.
     */
    public io.github.dfa1.vortex.fbs.ArrayStats fieldStats(int j) {
        return fieldStats(new io.github.dfa1.vortex.fbs.ArrayStats(), j);
    }

    public io.github.dfa1.vortex.fbs.ArrayStats fieldStats(io.github.dfa1.vortex.fbs.ArrayStats obj, int j) {
        int o = __offset(4);
        return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null;
    }

    public int fieldStatsLength() {
        int o = __offset(4);
        return o != 0 ? __vector_len(o) : 0;
    }

    public io.github.dfa1.vortex.fbs.ArrayStats.Vector fieldStatsVector() {
        return fieldStatsVector(new io.github.dfa1.vortex.fbs.ArrayStats.Vector());
    }

    public io.github.dfa1.vortex.fbs.ArrayStats.Vector fieldStatsVector(io.github.dfa1.vortex.fbs.ArrayStats.Vector obj) {
        int o = __offset(4);
        return o != 0 ? obj.__assign(__vector(o), 4, bb) : null;
    }

    public static final class Vector extends BaseVector {
        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public FileStatistics get(int j) {
            return get(new FileStatistics(), j);
        }

        public FileStatistics get(FileStatistics obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}

