// automatically generated by the FlatBuffers compiler, do not modify

package io.github.dfa1.vortex.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * The `Registry` object stores dictionary-encoded configuration for segments,
 * compression schemes, encryption schemes, etc.
 */
@SuppressWarnings("unused")
public final class Footer extends com.google.flatbuffers.Table {
  public static Footer getRootAsFooter(ByteBuffer _bb) { return getRootAsFooter(_bb, new Footer()); }
  public static Footer getRootAsFooter(ByteBuffer _bb, Footer obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Footer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public io.github.dfa1.vortex.fbs.ArraySpec arraySpecs(int j) { return arraySpecs(new io.github.dfa1.vortex.fbs.ArraySpec(), j); }
  public io.github.dfa1.vortex.fbs.ArraySpec arraySpecs(io.github.dfa1.vortex.fbs.ArraySpec obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int arraySpecsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public io.github.dfa1.vortex.fbs.ArraySpec.Vector arraySpecsVector() { return arraySpecsVector(new io.github.dfa1.vortex.fbs.ArraySpec.Vector()); }
  public io.github.dfa1.vortex.fbs.ArraySpec.Vector arraySpecsVector(io.github.dfa1.vortex.fbs.ArraySpec.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public io.github.dfa1.vortex.fbs.LayoutSpec layoutSpecs(int j) { return layoutSpecs(new io.github.dfa1.vortex.fbs.LayoutSpec(), j); }
  public io.github.dfa1.vortex.fbs.LayoutSpec layoutSpecs(io.github.dfa1.vortex.fbs.LayoutSpec obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int layoutSpecsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public io.github.dfa1.vortex.fbs.LayoutSpec.Vector layoutSpecsVector() { return layoutSpecsVector(new io.github.dfa1.vortex.fbs.LayoutSpec.Vector()); }
  public io.github.dfa1.vortex.fbs.LayoutSpec.Vector layoutSpecsVector(io.github.dfa1.vortex.fbs.LayoutSpec.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public io.github.dfa1.vortex.fbs.SegmentSpec segmentSpecs(int j) { return segmentSpecs(new io.github.dfa1.vortex.fbs.SegmentSpec(), j); }
  public io.github.dfa1.vortex.fbs.SegmentSpec segmentSpecs(io.github.dfa1.vortex.fbs.SegmentSpec obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o) + j * 16, bb) : null; }
  public int segmentSpecsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public io.github.dfa1.vortex.fbs.SegmentSpec.Vector segmentSpecsVector() { return segmentSpecsVector(new io.github.dfa1.vortex.fbs.SegmentSpec.Vector()); }
  public io.github.dfa1.vortex.fbs.SegmentSpec.Vector segmentSpecsVector(io.github.dfa1.vortex.fbs.SegmentSpec.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 16, bb) : null; }
  public io.github.dfa1.vortex.fbs.CompressionSpec compressionSpecs(int j) { return compressionSpecs(new io.github.dfa1.vortex.fbs.CompressionSpec(), j); }
  public io.github.dfa1.vortex.fbs.CompressionSpec compressionSpecs(io.github.dfa1.vortex.fbs.CompressionSpec obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int compressionSpecsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public io.github.dfa1.vortex.fbs.CompressionSpec.Vector compressionSpecsVector() { return compressionSpecsVector(new io.github.dfa1.vortex.fbs.CompressionSpec.Vector()); }
  public io.github.dfa1.vortex.fbs.CompressionSpec.Vector compressionSpecsVector(io.github.dfa1.vortex.fbs.CompressionSpec.Vector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public io.github.dfa1.vortex.fbs.EncryptionSpec encryptionSpecs(int j) { return encryptionSpecs(new io.github.dfa1.vortex.fbs.EncryptionSpec(), j); }
  public io.github.dfa1.vortex.fbs.EncryptionSpec encryptionSpecs(io.github.dfa1.vortex.fbs.EncryptionSpec obj, int j) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int encryptionSpecsLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public io.github.dfa1.vortex.fbs.EncryptionSpec.Vector encryptionSpecsVector() { return encryptionSpecsVector(new io.github.dfa1.vortex.fbs.EncryptionSpec.Vector()); }
  public io.github.dfa1.vortex.fbs.EncryptionSpec.Vector encryptionSpecsVector(io.github.dfa1.vortex.fbs.EncryptionSpec.Vector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createFooter(FlatBufferBuilder builder,
      int arraySpecsOffset,
      int layoutSpecsOffset,
      int segmentSpecsOffset,
      int compressionSpecsOffset,
      int encryptionSpecsOffset) {
    builder.startTable(5);
    Footer.addEncryptionSpecs(builder, encryptionSpecsOffset);
    Footer.addCompressionSpecs(builder, compressionSpecsOffset);
    Footer.addSegmentSpecs(builder, segmentSpecsOffset);
    Footer.addLayoutSpecs(builder, layoutSpecsOffset);
    Footer.addArraySpecs(builder, arraySpecsOffset);
    return Footer.endFooter(builder);
  }

  public static void startFooter(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addArraySpecs(FlatBufferBuilder builder, int arraySpecsOffset) { builder.addOffset(0, arraySpecsOffset, 0); }
  public static int createArraySpecsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startArraySpecsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addLayoutSpecs(FlatBufferBuilder builder, int layoutSpecsOffset) { builder.addOffset(1, layoutSpecsOffset, 0); }
  public static int createLayoutSpecsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startLayoutSpecsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addSegmentSpecs(FlatBufferBuilder builder, int segmentSpecsOffset) { builder.addOffset(2, segmentSpecsOffset, 0); }
  public static void startSegmentSpecsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(16, numElems, 8); }
  public static void addCompressionSpecs(FlatBufferBuilder builder, int compressionSpecsOffset) { builder.addOffset(3, compressionSpecsOffset, 0); }
  public static int createCompressionSpecsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startCompressionSpecsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addEncryptionSpecs(FlatBufferBuilder builder, int encryptionSpecsOffset) { builder.addOffset(4, encryptionSpecsOffset, 0); }
  public static int createEncryptionSpecsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startEncryptionSpecsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endFooter(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Footer get(int j) { return get(new Footer(), j); }
    public Footer get(Footer obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

