// automatically generated by the FlatBuffers compiler, do not modify

package io.github.dfa1.vortex.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.FlatBufferBuilder;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Null extends com.google.flatbuffers.Table {
    public static Null getRootAsNull(ByteBuffer _bb) {
        return getRootAsNull(_bb, new Null());
    }

    public static Null getRootAsNull(ByteBuffer _bb, Null obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public static void startNull(FlatBufferBuilder builder) {
        builder.startTable(0);
    }

    public static int endNull(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public Null __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public static final class Vector extends BaseVector {
        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public Null get(int j) {
            return get(new Null(), j);
        }

        public Null get(Null obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}

