// automatically generated by the FlatBuffers compiler, do not modify

package io.github.dfa1.vortex.fbs;

@SuppressWarnings("unused")
public final class Precision {
  private Precision() { }
  public static final int Inexact = 0;
  public static final int Exact = 1;

  public static final String[] names = { "Inexact", "Exact", };

  public static String name(int e) { return names[e]; }
}

