// automatically generated by the FlatBuffers compiler, do not modify

package io.github.dfa1.vortex.fbs;

@SuppressWarnings("unused")
public final class PType {
  private PType() { }
  public static final int U8 = 0;
  public static final int U16 = 1;
  public static final int U32 = 2;
  public static final int U64 = 3;
  public static final int I8 = 4;
  public static final int I16 = 5;
  public static final int I32 = 6;
  public static final int I64 = 7;
  public static final int F16 = 8;
  public static final int F32 = 9;
  public static final int F64 = 10;

  public static final String[] names = { "U8", "U16", "U32", "U64", "I8", "I16", "I32", "I64", "F16", "F32", "F64", };

  public static String name(int e) { return names[e]; }
}

