// automatically generated by the FlatBuffers compiler, do not modify

package io.github.dfa1.vortex.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Struct;

import java.nio.ByteBuffer;

/**
 * A `SegmentSpec` acts as the locator for a buffer within the file.
 */
@SuppressWarnings("unused")
public final class SegmentSpec extends Struct {
    public static int createSegmentSpec(FlatBufferBuilder builder, long offset, long length, int alignmentExponent, int _Compression, int _Encryption) {
        builder.prep(8, 16);
        builder.putShort((short) _Encryption);
        builder.putByte((byte) _Compression);
        builder.putByte((byte) alignmentExponent);
        builder.putInt((int) length);
        builder.putLong(offset);
        return builder.offset();
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public SegmentSpec __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    /**
     * Offset relative to the start of the file.
     */
    public long offset() {
        return bb.getLong(bb_pos + 0);
    }

    /**
     * Length in bytes of the segment.
     */
    public long length() {
        return (long) bb.getInt(bb_pos + 8) & 0xFFFFFFFFL;
    }

    /**
     * Base-2 exponent of the alignment of the segment.
     */
    public int alignmentExponent() {
        return bb.get(bb_pos + 12) & 0xFF;
    }

    public int _Compression() {
        return bb.get(bb_pos + 13) & 0xFF;
    }

    public int _Encryption() {
        return bb.getShort(bb_pos + 14) & 0xFFFF;
    }

    public static final class Vector extends BaseVector {
        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public SegmentSpec get(int j) {
            return get(new SegmentSpec(), j);
        }

        public SegmentSpec get(SegmentSpec obj, int j) {
            return obj.__assign(__element(j), bb);
        }
    }
}

