// automatically generated by the FlatBuffers compiler, do not modify

package io.github.dfa1.vortex.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Struct_ extends com.google.flatbuffers.Table {
  public static Struct_ getRootAsStruct_(ByteBuffer _bb) { return getRootAsStruct_(_bb, new Struct_()); }
  public static Struct_ getRootAsStruct_(ByteBuffer _bb, Struct_ obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Struct_ __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String names(int j) { int o = __offset(4); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int namesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public StringVector namesVector() { return namesVector(new StringVector()); }
  public StringVector namesVector(StringVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public io.github.dfa1.vortex.fbs.DType dtypes(int j) { return dtypes(new io.github.dfa1.vortex.fbs.DType(), j); }
  public io.github.dfa1.vortex.fbs.DType dtypes(io.github.dfa1.vortex.fbs.DType obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int dtypesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public io.github.dfa1.vortex.fbs.DType.Vector dtypesVector() { return dtypesVector(new io.github.dfa1.vortex.fbs.DType.Vector()); }
  public io.github.dfa1.vortex.fbs.DType.Vector dtypesVector(io.github.dfa1.vortex.fbs.DType.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public boolean nullable() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createStruct_(FlatBufferBuilder builder,
      int namesOffset,
      int dtypesOffset,
      boolean nullable) {
    builder.startTable(3);
    Struct_.addDtypes(builder, dtypesOffset);
    Struct_.addNames(builder, namesOffset);
    Struct_.addNullable(builder, nullable);
    return Struct_.endStruct_(builder);
  }

  public static void startStruct_(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addNames(FlatBufferBuilder builder, int namesOffset) { builder.addOffset(0, namesOffset, 0); }
  public static int createNamesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startNamesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addDtypes(FlatBufferBuilder builder, int dtypesOffset) { builder.addOffset(1, dtypesOffset, 0); }
  public static int createDtypesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startDtypesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addNullable(FlatBufferBuilder builder, boolean nullable) { builder.addBoolean(2, nullable, false); }
  public static int endStruct_(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Struct_ get(int j) { return get(new Struct_(), j); }
    public Struct_ get(Struct_ obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

