// automatically generated by the FlatBuffers compiler, do not modify

package io.github.dfa1.vortex.fbs;

@SuppressWarnings("unused")
public final class Type {
  private Type() { }
  public static final byte NONE = 0;
  public static final byte Null = 1;
  public static final byte Bool = 2;
  public static final byte Primitive = 3;
  public static final byte Decimal = 4;
  public static final byte Utf8 = 5;
  public static final byte Binary = 6;
  public static final byte Struct_ = 7;
  public static final byte List = 8;
  public static final byte Extension = 9;
  public static final byte FixedSizeList = 10;
  public static final byte Variant = 11;
  public static final byte Union = 12;

  public static final String[] names = { "NONE", "Null", "Bool", "Primitive", "Decimal", "Utf8", "Binary", "Struct_", "List", "Extension", "FixedSizeList", "Variant", "Union", };

  public static String name(int e) { return names[e]; }
}

