// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.core.fbs;

import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `ArrayStats` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsArrayStats extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsArrayStats getRootAsFbsArrayStats(MemorySegment seg) {
        return new FbsArrayStats().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsArrayStats assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the length of the `min` vector
    public int minLength() {
        int o = fieldOffset(4);
        return o != 0 ? vectorLength(o) : 0;
    }

    /// @param j element index
    /// @return the j-th `min` element
    public int min(int j) {
        int o = fieldOffset(4);
        return o != 0 ? readByte(vectorElements(o) + (long) j * 1) & 0xFF : 0;
    }

    /// @return a zero-copy slice of the `min` byte vector, or null if absent
    public MemorySegment minAsSegment() {
        int o = fieldOffset(4);
        return o != 0 ? byteVector(o) : null;
    }

    /// @return the `minPrecision` field
    public int minPrecision() {
        int o = fieldOffset(6);
        return o != 0 ? readByte(pos + o) & 0xFF : 0;
    }

    /// @return the length of the `max` vector
    public int maxLength() {
        int o = fieldOffset(8);
        return o != 0 ? vectorLength(o) : 0;
    }

    /// @param j element index
    /// @return the j-th `max` element
    public int max(int j) {
        int o = fieldOffset(8);
        return o != 0 ? readByte(vectorElements(o) + (long) j * 1) & 0xFF : 0;
    }

    /// @return a zero-copy slice of the `max` byte vector, or null if absent
    public MemorySegment maxAsSegment() {
        int o = fieldOffset(8);
        return o != 0 ? byteVector(o) : null;
    }

    /// @return the `maxPrecision` field
    public int maxPrecision() {
        int o = fieldOffset(10);
        return o != 0 ? readByte(pos + o) & 0xFF : 0;
    }

    /// @return the length of the `sum` vector
    public int sumLength() {
        int o = fieldOffset(12);
        return o != 0 ? vectorLength(o) : 0;
    }

    /// @param j element index
    /// @return the j-th `sum` element
    public int sum(int j) {
        int o = fieldOffset(12);
        return o != 0 ? readByte(vectorElements(o) + (long) j * 1) & 0xFF : 0;
    }

    /// @return a zero-copy slice of the `sum` byte vector, or null if absent
    public MemorySegment sumAsSegment() {
        int o = fieldOffset(12);
        return o != 0 ? byteVector(o) : null;
    }

    /// @return the `isSorted` field
    public boolean isSorted() {
        int o = fieldOffset(14);
        return o != 0 ? readByte(pos + o) != 0 : false;
    }

    /// @return whether the optional `isSorted` field is present
    public boolean hasIsSorted() {
        return fieldOffset(14) != 0;
    }

    /// @return the `isStrictSorted` field
    public boolean isStrictSorted() {
        int o = fieldOffset(16);
        return o != 0 ? readByte(pos + o) != 0 : false;
    }

    /// @return whether the optional `isStrictSorted` field is present
    public boolean hasIsStrictSorted() {
        return fieldOffset(16) != 0;
    }

    /// @return the `isConstant` field
    public boolean isConstant() {
        int o = fieldOffset(18);
        return o != 0 ? readByte(pos + o) != 0 : false;
    }

    /// @return whether the optional `isConstant` field is present
    public boolean hasIsConstant() {
        return fieldOffset(18) != 0;
    }

    /// @return the `nullCount` field
    public long nullCount() {
        int o = fieldOffset(20);
        return o != 0 ? readLong(pos + o) : 0L;
    }

    /// @return whether the optional `nullCount` field is present
    public boolean hasNullCount() {
        return fieldOffset(20) != 0;
    }

    /// @return the `uncompressedSizeInBytes` field
    public long uncompressedSizeInBytes() {
        int o = fieldOffset(22);
        return o != 0 ? readLong(pos + o) : 0L;
    }

    /// @return whether the optional `uncompressedSizeInBytes` field is present
    public boolean hasUncompressedSizeInBytes() {
        return fieldOffset(22) != 0;
    }

    /// @return the `nanCount` field
    public long nanCount() {
        int o = fieldOffset(24);
        return o != 0 ? readLong(pos + o) : 0L;
    }

    /// @return whether the optional `nanCount` field is present
    public boolean hasNanCount() {
        return fieldOffset(24) != 0;
    }

    /// Sets the `min` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addMin(FbsBuilder b, int offset) {
        b.addOffset(0, offset, 0);
    }

    /// Creates the `min` byte vector.
    /// @param b the builder
    /// @param data the bytes
    /// @return the vector offset
    public static int createMinVector(FbsBuilder b, byte[] data) {
        return b.createByteVector(data);
    }

    /// Begins the `min` vector.
    /// @param b the builder
    /// @param numElems element count
    public static void startMinVector(FbsBuilder b, int numElems) {
        b.startVector(1, numElems, 1);
    }

    /// Sets the `minPrecision` field.
    /// @param b the builder
    /// @param minPrecision value
    public static void addMinPrecision(FbsBuilder b, int minPrecision) {
        b.addByte(1, (byte) minPrecision, 0);
    }

    /// Sets the `max` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addMax(FbsBuilder b, int offset) {
        b.addOffset(2, offset, 0);
    }

    /// Creates the `max` byte vector.
    /// @param b the builder
    /// @param data the bytes
    /// @return the vector offset
    public static int createMaxVector(FbsBuilder b, byte[] data) {
        return b.createByteVector(data);
    }

    /// Begins the `max` vector.
    /// @param b the builder
    /// @param numElems element count
    public static void startMaxVector(FbsBuilder b, int numElems) {
        b.startVector(1, numElems, 1);
    }

    /// Sets the `maxPrecision` field.
    /// @param b the builder
    /// @param maxPrecision value
    public static void addMaxPrecision(FbsBuilder b, int maxPrecision) {
        b.addByte(3, (byte) maxPrecision, 0);
    }

    /// Sets the `sum` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addSum(FbsBuilder b, int offset) {
        b.addOffset(4, offset, 0);
    }

    /// Creates the `sum` byte vector.
    /// @param b the builder
    /// @param data the bytes
    /// @return the vector offset
    public static int createSumVector(FbsBuilder b, byte[] data) {
        return b.createByteVector(data);
    }

    /// Begins the `sum` vector.
    /// @param b the builder
    /// @param numElems element count
    public static void startSumVector(FbsBuilder b, int numElems) {
        b.startVector(1, numElems, 1);
    }

    /// Sets the `isSorted` field.
    /// @param b the builder
    /// @param isSorted value
    public static void addIsSorted(FbsBuilder b, boolean isSorted) {
        b.addBoolean(5, isSorted, false);
    }

    /// Sets the `isStrictSorted` field.
    /// @param b the builder
    /// @param isStrictSorted value
    public static void addIsStrictSorted(FbsBuilder b, boolean isStrictSorted) {
        b.addBoolean(6, isStrictSorted, false);
    }

    /// Sets the `isConstant` field.
    /// @param b the builder
    /// @param isConstant value
    public static void addIsConstant(FbsBuilder b, boolean isConstant) {
        b.addBoolean(7, isConstant, false);
    }

    /// Sets the `nullCount` field.
    /// @param b the builder
    /// @param nullCount value
    public static void addNullCount(FbsBuilder b, long nullCount) {
        b.addLong(8, nullCount, 0L);
    }

    /// Sets the `uncompressedSizeInBytes` field.
    /// @param b the builder
    /// @param uncompressedSizeInBytes value
    public static void addUncompressedSizeInBytes(FbsBuilder b, long uncompressedSizeInBytes) {
        b.addLong(9, uncompressedSizeInBytes, 0L);
    }

    /// Sets the `nanCount` field.
    /// @param b the builder
    /// @param nanCount value
    public static void addNanCount(FbsBuilder b, long nanCount) {
        b.addLong(10, nanCount, 0L);
    }

    /// Builds a `FbsArrayStats` table.
    /// @param b the builder
    /// @param minOffset field value
    /// @param minPrecision field value
    /// @param maxOffset field value
    /// @param maxPrecision field value
    /// @param sumOffset field value
    /// @param isSorted field value
    /// @param isStrictSorted field value
    /// @param isConstant field value
    /// @param nullCount field value
    /// @param uncompressedSizeInBytes field value
    /// @param nanCount field value
    /// @return the table offset
    public static int createFbsArrayStats(FbsBuilder b, int minOffset, int minPrecision, int maxOffset, int maxPrecision, int sumOffset, boolean isSorted, boolean isStrictSorted, boolean isConstant, long nullCount, long uncompressedSizeInBytes, long nanCount) {
        b.startTable(11);
        b.addLong(10, nanCount, 0L);
        b.addLong(9, uncompressedSizeInBytes, 0L);
        b.addLong(8, nullCount, 0L);
        b.addOffset(4, sumOffset, 0);
        b.addOffset(2, maxOffset, 0);
        b.addOffset(0, minOffset, 0);
        b.addBoolean(7, isConstant, false);
        b.addBoolean(6, isStrictSorted, false);
        b.addBoolean(5, isSorted, false);
        b.addByte(3, (byte) maxPrecision, 0);
        b.addByte(1, (byte) minPrecision, 0);
        return b.endTable();
    }

    /// Begins a `FbsArrayStats` table.
    /// @param b the builder
    public static void startFbsArrayStats(FbsBuilder b) {
        b.startTable(11);
    }

    /// Finishes a `FbsArrayStats` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsArrayStats(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsArrayStats` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsArrayStatsBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
