// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.core.fbs;

import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `ArraySpec` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsArraySpec extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsArraySpec getRootAsFbsArraySpec(MemorySegment seg) {
        return new FbsArraySpec().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsArraySpec assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the `id` field
    public String id() {
        int o = fieldOffset(4);
        return o != 0 ? readStringAt(pos + o) : null;
    }

    /// Sets the `id` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addId(FbsBuilder b, int offset) {
        b.addOffset(0, offset, 0);
    }

    /// Builds a `FbsArraySpec` table.
    /// @param b the builder
    /// @param idOffset field value
    /// @return the table offset
    public static int createFbsArraySpec(FbsBuilder b, int idOffset) {
        b.startTable(1);
        b.addOffset(0, idOffset, 0);
        return b.endTable();
    }

    /// Begins a `FbsArraySpec` table.
    /// @param b the builder
    public static void startFbsArraySpec(FbsBuilder b) {
        b.startTable(1);
    }

    /// Finishes a `FbsArraySpec` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsArraySpec(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsArraySpec` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsArraySpecBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
