// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.core.fbs;

import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `Array` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsArray extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsArray getRootAsFbsArray(MemorySegment seg) {
        return new FbsArray().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsArray assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the `root` child, or null if absent
    public FbsArrayNode root() {
        int o = fieldOffset(4);
        return o != 0 ? new FbsArrayNode().assign(seg, indirect(pos + o)) : null;
    }

    /// @return the length of the `buffers` vector
    public int buffersLength() {
        int o = fieldOffset(6);
        return o != 0 ? vectorLength(o) : 0;
    }

    /// @param j element index
    /// @return the j-th `buffers` element
    public FbsBuffer buffers(int j) {
        int o = fieldOffset(6);
        return new FbsBuffer().assign(seg, vectorElements(o) + (long) j * 8);
    }

    /// Sets the `root` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addRoot(FbsBuilder b, int offset) {
        b.addOffset(0, offset, 0);
    }

    /// Sets the `buffers` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addBuffers(FbsBuilder b, int offset) {
        b.addOffset(1, offset, 0);
    }

    /// Begins the `buffers` vector.
    /// @param b the builder
    /// @param numElems element count
    public static void startBuffersVector(FbsBuilder b, int numElems) {
        b.startVector(8, numElems, 4);
    }

    /// Builds a `FbsArray` table.
    /// @param b the builder
    /// @param rootOffset field value
    /// @param buffersOffset field value
    /// @return the table offset
    public static int createFbsArray(FbsBuilder b, int rootOffset, int buffersOffset) {
        b.startTable(2);
        b.addOffset(1, buffersOffset, 0);
        b.addOffset(0, rootOffset, 0);
        return b.endTable();
    }

    /// Begins a `FbsArray` table.
    /// @param b the builder
    public static void startFbsArray(FbsBuilder b) {
        b.startTable(2);
    }

    /// Finishes a `FbsArray` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsArray(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsArray` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsArrayBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
