// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.core.fbs;

import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `CompressionSpec` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsCompressionSpec extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsCompressionSpec getRootAsFbsCompressionSpec(MemorySegment seg) {
        return new FbsCompressionSpec().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsCompressionSpec assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the `scheme` field
    public int scheme() {
        int o = fieldOffset(4);
        return o != 0 ? readByte(pos + o) & 0xFF : 0;
    }

    /// Sets the `scheme` field.
    /// @param b the builder
    /// @param scheme value
    public static void addScheme(FbsBuilder b, int scheme) {
        b.addByte(0, (byte) scheme, 0);
    }

    /// Builds a `FbsCompressionSpec` table.
    /// @param b the builder
    /// @param scheme field value
    /// @return the table offset
    public static int createFbsCompressionSpec(FbsBuilder b, int scheme) {
        b.startTable(1);
        b.addByte(0, (byte) scheme, 0);
        return b.endTable();
    }

    /// Begins a `FbsCompressionSpec` table.
    /// @param b the builder
    public static void startFbsCompressionSpec(FbsBuilder b) {
        b.startTable(1);
    }

    /// Finishes a `FbsCompressionSpec` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsCompressionSpec(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsCompressionSpec` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsCompressionSpecBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
