// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.core.fbs;

import javax.annotation.processing.Generated;

/// Constants for the `CompressionScheme` FlatBuffers enum.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsCompressionScheme {

    private FbsCompressionScheme() {
    }

    /// `None` = 0
    public static final byte None = (byte) 0;

    /// `LZ4` = 1
    public static final byte LZ4 = (byte) 1;

    /// `ZLib` = 2
    public static final byte ZLib = (byte) 2;

    /// `ZStd` = 3
    public static final byte ZStd = (byte) 3;
}
