// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.core.fbs;

import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `EncryptionSpec` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsEncryptionSpec extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsEncryptionSpec getRootAsFbsEncryptionSpec(MemorySegment seg) {
        return new FbsEncryptionSpec().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsEncryptionSpec assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// Builds a `FbsEncryptionSpec` table.
    /// @param b the builder
    /// @return the table offset
    public static int createFbsEncryptionSpec(FbsBuilder b) {
        b.startTable(0);
        return b.endTable();
    }

    /// Begins a `FbsEncryptionSpec` table.
    /// @param b the builder
    public static void startFbsEncryptionSpec(FbsBuilder b) {
        b.startTable(0);
    }

    /// Finishes a `FbsEncryptionSpec` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsEncryptionSpec(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsEncryptionSpec` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsEncryptionSpecBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
