// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.core.fbs;

import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `Extension` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsExtension extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsExtension getRootAsFbsExtension(MemorySegment seg) {
        return new FbsExtension().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsExtension assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the `id` field
    public String id() {
        int o = fieldOffset(4);
        return o != 0 ? readStringAt(pos + o) : null;
    }

    /// @return the `storageDtype` child, or null if absent
    public FbsDType storageDtype() {
        int o = fieldOffset(6);
        return o != 0 ? new FbsDType().assign(seg, indirect(pos + o)) : null;
    }

    /// @return the length of the `metadata` vector
    public int metadataLength() {
        int o = fieldOffset(8);
        return o != 0 ? vectorLength(o) : 0;
    }

    /// @param j element index
    /// @return the j-th `metadata` element
    public int metadata(int j) {
        int o = fieldOffset(8);
        return o != 0 ? readByte(vectorElements(o) + (long) j * 1) & 0xFF : 0;
    }

    /// @return a zero-copy slice of the `metadata` byte vector, or null if absent
    public MemorySegment metadataAsSegment() {
        int o = fieldOffset(8);
        return o != 0 ? byteVector(o) : null;
    }

    /// Sets the `id` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addId(FbsBuilder b, int offset) {
        b.addOffset(0, offset, 0);
    }

    /// Sets the `storageDtype` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addStorageDtype(FbsBuilder b, int offset) {
        b.addOffset(1, offset, 0);
    }

    /// Sets the `metadata` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addMetadata(FbsBuilder b, int offset) {
        b.addOffset(2, offset, 0);
    }

    /// Creates the `metadata` byte vector.
    /// @param b the builder
    /// @param data the bytes
    /// @return the vector offset
    public static int createMetadataVector(FbsBuilder b, byte[] data) {
        return b.createByteVector(data);
    }

    /// Begins the `metadata` vector.
    /// @param b the builder
    /// @param numElems element count
    public static void startMetadataVector(FbsBuilder b, int numElems) {
        b.startVector(1, numElems, 1);
    }

    /// Builds a `FbsExtension` table.
    /// @param b the builder
    /// @param idOffset field value
    /// @param storageDtypeOffset field value
    /// @param metadataOffset field value
    /// @return the table offset
    public static int createFbsExtension(FbsBuilder b, int idOffset, int storageDtypeOffset, int metadataOffset) {
        b.startTable(3);
        b.addOffset(2, metadataOffset, 0);
        b.addOffset(1, storageDtypeOffset, 0);
        b.addOffset(0, idOffset, 0);
        return b.endTable();
    }

    /// Begins a `FbsExtension` table.
    /// @param b the builder
    public static void startFbsExtension(FbsBuilder b) {
        b.startTable(3);
    }

    /// Finishes a `FbsExtension` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsExtension(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsExtension` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsExtensionBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
