// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.core.fbs;

import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `List` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsList extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsList getRootAsFbsList(MemorySegment seg) {
        return new FbsList().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsList assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the `elementType` child, or null if absent
    public FbsDType elementType() {
        int o = fieldOffset(4);
        return o != 0 ? new FbsDType().assign(seg, indirect(pos + o)) : null;
    }

    /// @return the `nullable` field
    public boolean nullable() {
        int o = fieldOffset(6);
        return o != 0 ? readByte(pos + o) != 0 : false;
    }

    /// Sets the `elementType` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addElementType(FbsBuilder b, int offset) {
        b.addOffset(0, offset, 0);
    }

    /// Sets the `nullable` field.
    /// @param b the builder
    /// @param nullable value
    public static void addNullable(FbsBuilder b, boolean nullable) {
        b.addBoolean(1, nullable, false);
    }

    /// Builds a `FbsList` table.
    /// @param b the builder
    /// @param elementTypeOffset field value
    /// @param nullable field value
    /// @return the table offset
    public static int createFbsList(FbsBuilder b, int elementTypeOffset, boolean nullable) {
        b.startTable(2);
        b.addOffset(0, elementTypeOffset, 0);
        b.addBoolean(1, nullable, false);
        return b.endTable();
    }

    /// Begins a `FbsList` table.
    /// @param b the builder
    public static void startFbsList(FbsBuilder b) {
        b.startTable(2);
    }

    /// Finishes a `FbsList` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsList(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsList` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsListBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
