// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.core.fbs;

import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `Map` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsMap extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsMap getRootAsFbsMap(MemorySegment seg) {
        return new FbsMap().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsMap assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the `keyType` child, or null if absent
    public FbsDType keyType() {
        int o = fieldOffset(4);
        return o != 0 ? new FbsDType().assign(seg, indirect(pos + o)) : null;
    }

    /// @return the `valueType` child, or null if absent
    public FbsDType valueType() {
        int o = fieldOffset(6);
        return o != 0 ? new FbsDType().assign(seg, indirect(pos + o)) : null;
    }

    /// @return the `keysSorted` field
    public boolean keysSorted() {
        int o = fieldOffset(8);
        return o != 0 ? readByte(pos + o) != 0 : false;
    }

    /// @return the `nullable` field
    public boolean nullable() {
        int o = fieldOffset(10);
        return o != 0 ? readByte(pos + o) != 0 : false;
    }

    /// Sets the `keyType` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addKeyType(FbsBuilder b, int offset) {
        b.addOffset(0, offset, 0);
    }

    /// Sets the `valueType` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addValueType(FbsBuilder b, int offset) {
        b.addOffset(1, offset, 0);
    }

    /// Sets the `keysSorted` field.
    /// @param b the builder
    /// @param keysSorted value
    public static void addKeysSorted(FbsBuilder b, boolean keysSorted) {
        b.addBoolean(2, keysSorted, false);
    }

    /// Sets the `nullable` field.
    /// @param b the builder
    /// @param nullable value
    public static void addNullable(FbsBuilder b, boolean nullable) {
        b.addBoolean(3, nullable, false);
    }

    /// Builds a `FbsMap` table.
    /// @param b the builder
    /// @param keyTypeOffset field value
    /// @param valueTypeOffset field value
    /// @param keysSorted field value
    /// @param nullable field value
    /// @return the table offset
    public static int createFbsMap(FbsBuilder b, int keyTypeOffset, int valueTypeOffset, boolean keysSorted, boolean nullable) {
        b.startTable(4);
        b.addOffset(1, valueTypeOffset, 0);
        b.addOffset(0, keyTypeOffset, 0);
        b.addBoolean(3, nullable, false);
        b.addBoolean(2, keysSorted, false);
        return b.endTable();
    }

    /// Begins a `FbsMap` table.
    /// @param b the builder
    public static void startFbsMap(FbsBuilder b) {
        b.startTable(4);
    }

    /// Finishes a `FbsMap` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsMap(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsMap` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsMapBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
