// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.core.fbs;

import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `Primitive` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsPrimitive extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsPrimitive getRootAsFbsPrimitive(MemorySegment seg) {
        return new FbsPrimitive().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsPrimitive assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the `ptype` field
    public int ptype() {
        int o = fieldOffset(4);
        return o != 0 ? readByte(pos + o) & 0xFF : 0;
    }

    /// @return the `nullable` field
    public boolean nullable() {
        int o = fieldOffset(6);
        return o != 0 ? readByte(pos + o) != 0 : false;
    }

    /// Sets the `ptype` field.
    /// @param b the builder
    /// @param ptype value
    public static void addPtype(FbsBuilder b, int ptype) {
        b.addByte(0, (byte) ptype, 0);
    }

    /// Sets the `nullable` field.
    /// @param b the builder
    /// @param nullable value
    public static void addNullable(FbsBuilder b, boolean nullable) {
        b.addBoolean(1, nullable, false);
    }

    /// Builds a `FbsPrimitive` table.
    /// @param b the builder
    /// @param ptype field value
    /// @param nullable field value
    /// @return the table offset
    public static int createFbsPrimitive(FbsBuilder b, int ptype, boolean nullable) {
        b.startTable(2);
        b.addBoolean(1, nullable, false);
        b.addByte(0, (byte) ptype, 0);
        return b.endTable();
    }

    /// Begins a `FbsPrimitive` table.
    /// @param b the builder
    public static void startFbsPrimitive(FbsBuilder b) {
        b.startTable(2);
    }

    /// Finishes a `FbsPrimitive` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsPrimitive(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsPrimitive` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsPrimitiveBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
