// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.core.fbs;

import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `SegmentSpec` FlatBuffers struct (inline, 16 bytes).
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsSegmentSpec extends FbsStruct {

    /// Positions this reader at a struct.
    /// @param seg the buffer
    /// @param position the struct position
    /// @return this
    public FbsSegmentSpec assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the `offset` field
    public long offset() {
        return readLong(0);
    }

    /// @return the `length` field
    public long length() {
        return readInt(8) & 0xFFFFFFFFL;
    }

    /// @return the `alignmentExponent` field
    public int alignmentExponent() {
        return readByte(12) & 0xFF;
    }

    /// @return the `compression` field
    public int compression() {
        return readByte(13) & 0xFF;
    }

    /// @return the `encryption` field
    public int encryption() {
        return readShort(14) & 0xFFFF;
    }

    /// Writes an inline `FbsSegmentSpec` struct.
    /// @param b the builder
    /// @param offset field value
    /// @param length field value
    /// @param alignmentExponent field value
    /// @param compression field value
    /// @param encryption field value
    /// @return the struct offset
    public static int createFbsSegmentSpec(FbsBuilder b, long offset, long length, int alignmentExponent, int compression, int encryption) {
        b.prep(8, 16);
        b.putShort((short) encryption);
        b.putByte((byte) compression);
        b.putByte((byte) alignmentExponent);
        b.putInt((int) length);
        b.putLong(offset);
        return b.offset();
    }
}
