// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.core.fbs;

import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;

/// Reader and builder for the `Struct_` FlatBuffers table.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsStruct extends FbsTable {

    /// Positions a reader at the root table of a finished buffer.
    /// @param seg the buffer
    /// @return a reader positioned at the root
    public static FbsStruct getRootAsFbsStruct(MemorySegment seg) {
        return new FbsStruct().assign(seg, FbsTable.rootPosition(seg, 0));
    }

    /// Positions this reader at a table.
    /// @param seg the buffer
    /// @param position the table position
    /// @return this
    public FbsStruct assign(MemorySegment seg, long position) {
        init(seg, position);
        return this;
    }

    /// @return the length of the `names` vector
    public int namesLength() {
        int o = fieldOffset(4);
        return o != 0 ? vectorLength(o) : 0;
    }

    /// @param j element index
    /// @return the j-th `names` string
    public String names(int j) {
        int o = fieldOffset(4);
        return readStringAt(vectorElements(o) + (long) j * 4);
    }

    /// @return the length of the `dtypes` vector
    public int dtypesLength() {
        int o = fieldOffset(6);
        return o != 0 ? vectorLength(o) : 0;
    }

    /// @param j element index
    /// @return the j-th `dtypes` element
    public FbsDType dtypes(int j) {
        int o = fieldOffset(6);
        return new FbsDType().assign(seg, indirect(vectorElements(o) + (long) j * 4));
    }

    /// @return the `nullable` field
    public boolean nullable() {
        int o = fieldOffset(8);
        return o != 0 ? readByte(pos + o) != 0 : false;
    }

    /// Sets the `names` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addNames(FbsBuilder b, int offset) {
        b.addOffset(0, offset, 0);
    }

    /// Creates the `names` offset vector.
    /// @param b the builder
    /// @param data element offsets
    /// @return the vector offset
    public static int createNamesVector(FbsBuilder b, int[] data) {
        b.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) {
            b.addOffset(data[i]);
        }
        return b.endVector();
    }

    /// Begins the `names` vector.
    /// @param b the builder
    /// @param numElems element count
    public static void startNamesVector(FbsBuilder b, int numElems) {
        b.startVector(4, numElems, 4);
    }

    /// Sets the `dtypes` offset field.
    /// @param b the builder
    /// @param offset the referenced offset
    public static void addDtypes(FbsBuilder b, int offset) {
        b.addOffset(1, offset, 0);
    }

    /// Creates the `dtypes` offset vector.
    /// @param b the builder
    /// @param data element offsets
    /// @return the vector offset
    public static int createDtypesVector(FbsBuilder b, int[] data) {
        b.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) {
            b.addOffset(data[i]);
        }
        return b.endVector();
    }

    /// Begins the `dtypes` vector.
    /// @param b the builder
    /// @param numElems element count
    public static void startDtypesVector(FbsBuilder b, int numElems) {
        b.startVector(4, numElems, 4);
    }

    /// Sets the `nullable` field.
    /// @param b the builder
    /// @param nullable value
    public static void addNullable(FbsBuilder b, boolean nullable) {
        b.addBoolean(2, nullable, false);
    }

    /// Builds a `FbsStruct` table.
    /// @param b the builder
    /// @param namesOffset field value
    /// @param dtypesOffset field value
    /// @param nullable field value
    /// @return the table offset
    public static int createFbsStruct(FbsBuilder b, int namesOffset, int dtypesOffset, boolean nullable) {
        b.startTable(3);
        b.addOffset(1, dtypesOffset, 0);
        b.addOffset(0, namesOffset, 0);
        b.addBoolean(2, nullable, false);
        return b.endTable();
    }

    /// Begins a `FbsStruct` table.
    /// @param b the builder
    public static void startFbsStruct(FbsBuilder b) {
        b.startTable(3);
    }

    /// Finishes a `FbsStruct` table.
    /// @param b the builder
    /// @return the table offset
    public static int endFbsStruct(FbsBuilder b) {
        return b.endTable();
    }

    /// Finishes the buffer with a `FbsStruct` root.
    /// @param b the builder
    /// @param offset the root table offset
    public static void finishFbsStructBuffer(FbsBuilder b, int offset) {
        b.finish(offset);
    }
}
