// Generated by vortex-fbs-gen. Do not edit.

package io.github.dfa1.vortex.core.fbs;

import javax.annotation.processing.Generated;

/// Discriminator constants for the `Type` FlatBuffers union.
@Generated("io.github.dfa1.vortex.fbsgen.CodeGen")
public final class FbsType {

    private FbsType() {
    }

    /// No member selected.
    public static final byte NONE = 0;

    /// Member `Null` = 1
    public static final byte FbsNull = (byte) 1;

    /// Member `Bool` = 2
    public static final byte FbsBool = (byte) 2;

    /// Member `Primitive` = 3
    public static final byte FbsPrimitive = (byte) 3;

    /// Member `Decimal` = 4
    public static final byte FbsDecimal = (byte) 4;

    /// Member `Utf8` = 5
    public static final byte FbsUtf8 = (byte) 5;

    /// Member `Binary` = 6
    public static final byte FbsBinary = (byte) 6;

    /// Member `Struct_` = 7
    public static final byte FbsStruct_ = (byte) 7;

    /// Member `List` = 8
    public static final byte FbsList = (byte) 8;

    /// Member `Extension` = 9
    public static final byte FbsExtension = (byte) 9;

    /// Member `FixedSizeList` = 10
    public static final byte FbsFixedSizeList = (byte) 10;

    /// Member `Variant` = 11
    public static final byte FbsVariant = (byte) 11;

    /// Member `Union` = 12
    public static final byte FbsUnion = (byte) 12;
}
